// ReSharper disable All
namespace KairosWebAPI.Models.ResponseResults;

public class EmpBasicSvcRes
{
    public string? Company { get; set; }
    public string? EmpID { get; set; }
    public string? FirstName { get; set; }
    public string? MiddleInitial { get; set; }
    public string? LastName { get; set; }
    public string? Name { get; set; }
    public string? Address { get; set; }
    public string? Address2 { get; set; }
    public string? City { get; set; }
    public string? State { get; set; }
    public string? ZIP { get; set; }
    public string? Country { get; set; }
    public string? Phone { get; set; }
    public string? EmgPhone { get; set; }
    public int? Shift { get; set; }
    public object? LaborRate { get; set; }
    public bool Payroll { get; set; }
    public bool PRSetupReq { get; set; }
    public string? EmpStatus { get; set; }
    public string? ExpenseCode { get; set; }
    public string? PhotoFile { get; set; }
    public string? JCDept { get; set; }
    public string? EmgContact { get; set; }
    public string? SupervisorID { get; set; }
    public int? CountryNum { get; set; }
    public bool ServTech { get; set; }
    public string? EMailAddress { get; set; }
    public string? DcdUserID { get; set; }
    public bool ProductionWorker { get; set; }
    public bool MaterialHandler { get; set; }
    public bool ShopSupervisor { get; set; }
    public bool CanReportQty { get; set; }
    public bool CanOverrideJob { get; set; }
    public bool CanRequestMaterial { get; set; }
    public bool CanReportScrapQty { get; set; }
    public bool CanReportNCQty { get; set; }
    public bool ShipRecv { get; set; }
    public string? CnvEmpID { get; set; }
    public bool WarehouseManager { get; set; }
    public bool CanOverrideAllocations { get; set; }
    public bool AllowDirLbr { get; set; }
    public bool ContractEmp { get; set; }
    public string? ResourceGrpID { get; set; }
    public string? ResourceID { get; set; }
    public string? TimeWFGroupID { get; set; }
    public bool ExpenseEntryAllowed { get; set; }
    public string? ExpenseWFGroupID { get; set; }
    public int? ExpenseVendorNum { get; set; }
    public int? PerConID { get; set; }
    public bool SyncNameToPerCon { get; set; }
    public bool SyncAddressToPerCon { get; set; }
    public bool SyncPhoneToPerCon { get; set; }
    public bool SyncEmailToPerCon { get; set; }
    public bool CanEnterIndirectTime { get; set; }
    public bool CanEnterProductionTime { get; set; }
    public bool CanEnterProjectTime { get; set; }
    public bool CanEnterServiceTime { get; set; }
    public bool CanEnterSetupTime { get; set; }
    public bool TimeAutoApprove { get; set; }
    public bool ExpenseAutoApprove { get; set; }
    public string? MobileUserPassword { get; set; }
    public bool AllowIndirect { get; set; }
    public bool AllowProduction { get; set; }
    public bool AllowProject { get; set; }
    public bool AllowService { get; set; }
    public bool AllowSetup { get; set; }
    public string? DefaultLaborTypePseudo { get; set; }
    public string? DefaultTimeTypCd { get; set; }
    public string? DefaultIndirectCode { get; set; }
    public string? DefaultExpenseCode { get; set; }
    public string? DefaultResourceGrpID { get; set; }
    public string? DefaultResourceID { get; set; }
    public object? DefaultLaborHrs { get; set; }
    public string? DefaultExpCurrencyCode { get; set; }
    public string? DefaultClaimCurrencyCode { get; set; }
    public int? DefaultPMUID { get; set; }
    public string? DefaultTaxRegionCode { get; set; }
    public bool DefaultTaxIncluded { get; set; }
    public bool ExpenseAdvReqAllowed { get; set; }
    public string? ExpenseAdvReqWFGroupID { get; set; }
    public bool ExpenseAdvReqAutoApprove { get; set; }
    public string? MobileResourceID { get; set; }
    public bool AllowAsAltRemitTo { get; set; }
    public string? UserNameInJDF { get; set; }
    public bool ExternalMES { get; set; }
    public bool PermitScrap { get; set; }
    public bool PermitDown { get; set; }
    public bool PermitHelp { get; set; }
    public bool PermitJobControl { get; set; }
    public bool PermitNextJobControl { get; set; }
    public bool PermitManualSqc { get; set; }
    public bool PermitVariableSqc { get; set; }
    public bool PermitAttributeSqc { get; set; }
    public bool PermitMaterialLot { get; set; }
    public bool PermitSetupMaterial { get; set; }
    public bool PermitCavities { get; set; }
    public bool PermitPercentRegrind { get; set; }
    public bool PermitSaveProfile { get; set; }
    public bool PermitCalibration { get; set; }
    public bool PermitMachinePm { get; set; }
    public bool PermitToolPm { get; set; }
    public bool PermitLanguage { get; set; }
    public bool PermitPreferences { get; set; }
    public object? SysRevID { get; set; }
    public object? SysRowID { get; set; }
    public bool DisallowTimeEntry { get; set; }
    public bool PkgInboundAllowed { get; set; }
    public bool PkgOutboundAllowed { get; set; }
    public bool PkgInventoryAllowed { get; set; }
    public bool PkgManufacturingAllowed { get; set; }
    public bool PkgQualityAllowed { get; set; }
    public string? ImageID { get; set; }
    public bool PkgMasterMixedPrint { get; set; }
    public bool PkgSuppressPrintMessages { get; set; }
    public string? PayrollValuesForHCM { get; set; }
    public bool SendToFSA { get; set; }
    public bool ExternalMESSyncRequired { get; set; }
    public object? ExternalMESLastSync { get; set; }
    public string? IDDocument { get; set; }
    public object? BirthDate { get; set; }
    public string? Sex { get; set; }
    public string? Department { get; set; }
    public object? EnrollmentDate { get; set; }
    public object? DepartureDate { get; set; }
    public bool AlertFlag { get; set; }
    public string? DepartmentDescription { get; set; }
    public bool EnableExpenseSupplier { get; set; }
    public string? ExpenseDescription { get; set; }
    public bool ExpenseDisableCreate { get; set; }
    public bool ExpenseRestrictEntry { get; set; }
    public bool FoundPayroll { get; set; }
    public bool FoundPayrollUserAllowed { get; set; }
    public string? HCMEnabledAt { get; set; }
    public bool IsHCMAllowedByEmp { get; set; }
    public string? PayrollValuesForHCMDsp { get; set; }
    public string? PerConName { get; set; }
    public string? PhotoFilePath { get; set; }
    public bool SetShopLoad { get; set; }
    public string? ShiftEndTime { get; set; }
    public string? ShiftStartTime { get; set; }
    public string? SupervisorName { get; set; }
    public bool TimeDisableCreate { get; set; }
    public bool TimeRestrictEntry { get; set; }
    public string? UserIDName { get; set; }
    public string? CalendarID { get; set; }
    public string? COASegReferences { get; set; }
    public string? TimeApprovalTasksTree { get; set; }
    public string? ExpenseApprovalTasksTree { get; set; }
    public object? ShiftLength { get; set; }
    public int? BitFlag { get; set; }
    public bool CompanySendToFSA { get; set; }
    public string? CountryNumDescription { get; set; }
    public string? ExpenseCodeDescription { get; set; }
    public string? ExpenseVendorNumName { get; set; }
    public string? ExpenseVendorNumCity { get; set; }
    public string? ExpenseVendorNumTermsCode { get; set; }
    public string? ExpenseVendorNumAddress3 { get; set; }
    public string? ExpenseVendorNumDefaultFOB { get; set; }
    public string? ExpenseVendorNumCurrencyCode { get; set; }
    public string? ExpenseVendorNumZIP { get; set; }
    public string? ExpenseVendorNumVendorID { get; set; }
    public string? ExpenseVendorNumAddress2 { get; set; }
    public string? ExpenseVendorNumAddress1 { get; set; }
    public string? ExpenseVendorNumCountry { get; set; }
    public string? ExpenseVendorNumState { get; set; }
    public string? JCDeptDescription { get; set; }
    public string? MachineDescription { get; set; }
    public string? ResourceDescription { get; set; }
    public string? ResourceGroupDescription { get; set; }
    public string? ShiftDescription { get; set; }
    public string? RowMod { get; set; }
    public object? UD_SysRevID { get; set; }
    public bool AllowOvertime_c { get; set; }
    public bool CertOfConfSignOff_c { get; set; }
    public string? JobTitle_c { get; set; }
    public bool KResetPass_c { get; set; }
    public bool KTestCell_c { get; set; }
    public bool RMAContact_c { get; set; }
    public string? SecIC_c { get; set; }
    public bool SecICAppTime_c { get; set; }
}