// ReSharper disable InconsistentNaming
namespace KairosWebAPI.Models.ResponseResults.Shipment
{

    public class KShipmentResponse
    {
        public string? Company { get; set; }
        public int? PackNum { get; set; }
        public DateTime? ShipDate { get; set; }
        public string? ShipViaCode { get; set; }
        public string? ShipPerson { get; set; }
        public string? EntryPerson { get; set; }
        public string? ShipLog { get; set; }
        public string? LabelComment { get; set; }
        public string? ShipComment { get; set; }
        public bool Invoiced { get; set; }
        public string? ShipToNum { get; set; }
        public bool ReadyToInvoice { get; set; }
        public decimal? CustNum { get; set; }
        public string? Plant { get; set; }
        public string? TrackingNumber { get; set; }
        public string? LegalNumber { get; set; }
        public bool Voided { get; set; }
        public bool ExternalDeliveryNote { get; set; }
        public string? ExternalID { get; set; }
        public bool ICReceived { get; set; }
        public string? XRefPackNum { get; set; }
        public decimal? BTCustNum { get; set; }
        public decimal? BTConNum { get; set; }
        public string? ShipStatus { get; set; }
        public string? ShipGroup { get; set; }
        public string? PkgCode { get; set; }
        public string? PkgClass { get; set; }
        public decimal? Weight { get; set; }
        public bool ResDelivery { get; set; }
        public bool SatDelivery { get; set; }
        public bool SatPickup { get; set; }
        public bool VerbalConf { get; set; }
        public bool Hazmat { get; set; }
        public bool DocOnly { get; set; }
        public string? RefNotes { get; set; }
        public bool ApplyChrg { get; set; }
        public decimal? ChrgAmount { get; set; }
        public bool COD { get; set; }
        public bool CODFreight { get; set; }
        public bool CODCheck { get; set; }
        public decimal? CODAmount { get; set; }
        public string? GroundType { get; set; }
        public bool NotifyFlag { get; set; }
        public string? NotifyEMail { get; set; }
        public bool DeclaredIns { get; set; }
        public decimal? DeclaredAmt { get; set; }
        public string? MFTransNum { get; set; }
        public string? MFCallTag { get; set; }
        public string? MFPickupNum { get; set; }
        public decimal? MFDiscFreight { get; set; }
        public string? MFTemplate { get; set; }
        public bool MFUse3B { get; set; }
        public string? MF3BAccount { get; set; }
        public decimal? MFDimWeight { get; set; }
        public string? MFZone { get; set; }
        public decimal? MFFreightAmt { get; set; }
        public decimal? MFOtherAmt { get; set; }
        public bool MFOversized { get; set; }
        public bool ServSatDelivery { get; set; }
        public bool ServSatPickup { get; set; }
        public bool ServSignature { get; set; }
        public bool ServAlert { get; set; }
        public bool ServPOD { get; set; }
        public bool ServAOD { get; set; }
        public bool ServHomeDel { get; set; }
        public string? DeliveryType { get; set; }
        public DateTime? ServDeliveryDate { get; set; }
        public string? ServPhone { get; set; }
        public string? ServInstruct { get; set; }
        public bool ServRelease { get; set; }
        public string? ServAuthNum { get; set; }
        public string? ServRef1 { get; set; }
        public string? ServRef2 { get; set; }
        public string? ServRef3 { get; set; }
        public string? ServRef4 { get; set; }
        public string? ServRef5 { get; set; }
        public decimal? BOLNum { get; set; }
        public decimal? BOLLine { get; set; }
        public bool CommercialInvoice { get; set; }
        public bool ShipExprtDeclartn { get; set; }
        public bool CertOfOrigin { get; set; }
        public bool LetterOfInstr { get; set; }
        public bool HazardousShipment { get; set; }
        public bool IntrntlShip { get; set; }
        public string? PayFlag { get; set; }
        public string? PayAccount { get; set; }
        public string? PayBTAddress1 { get; set; }
        public string? PayBTAddress2 { get; set; }
        public string? PayBTCity { get; set; }
        public string? PayBTState { get; set; }
        public string? PayBTZip { get; set; }
        public string? PayBTCountry { get; set; }
        public string? FFAddress1 { get; set; }
        public string? FFAddress2 { get; set; }
        public string? FFCity { get; set; }
        public string? FFState { get; set; }
        public string? FFZip { get; set; }
        public string? FFCountry { get; set; }
        public string? FFContact { get; set; }
        public string? FFCompName { get; set; }
        public string? FFPhoneNum { get; set; }
        public string? ChangedBy { get; set; }
        public DateTime? ChangeDate { get; set; }
        public decimal? ChangeTime { get; set; }
        public string? FFID { get; set; }
        public bool IndividualPackIDs { get; set; }
        public string? FFAddress3 { get; set; }
        public decimal? DeliveryConf { get; set; }
        public bool AddlHdlgFlag { get; set; }
        public bool NonStdPkg { get; set; }
        public decimal? FFCountryNum { get; set; }
        public string? PayBTAddress3 { get; set; }
        public decimal? PayBTCountryNum { get; set; }
        public string? PayBTPhone { get; set; }
        public string? WayBillNbr { get; set; }
        public string? FreightedShipViaCode { get; set; }
        public bool UPSQuantumView { get; set; }
        public string? UPSQVShipFromName { get; set; }
        public string? UPSQVMemo { get; set; }
        public decimal? PkgLength { get; set; }
        public decimal? PkgWidth { get; set; }
        public decimal? PkgHeight { get; set; }
        public bool EDIReady { get; set; }
        public bool PhantomPack { get; set; }
        public decimal? ReplicatedFrom { get; set; }
        public string? ReplicatedStat { get; set; }
        public string? PkgSizeUOM { get; set; }
        public string? WeightUOM { get; set; }
        public bool UseOTS { get; set; }
        public string? TranDocTypeID { get; set; }
        public bool DocumentPrinted { get; set; }
        public decimal? OTSOrderNum { get; set; }
        public bool TaxCalculated { get; set; }
        public DateTime? TaxCalcDate { get; set; }
        public string? CurrencyCode { get; set; }
        public decimal? Rounding { get; set; }
        public decimal? Rpt1Rounding { get; set; }
        public decimal? Rpt2Rounding { get; set; }
        public decimal? Rpt3Rounding { get; set; }
        public decimal? DocRounding { get; set; }
        public decimal? Rpt1TotalTax { get; set; }
        public decimal? Rpt2TotalTax { get; set; }
        public decimal? Rpt3TotalTax { get; set; }
        public decimal? OrderAmt { get; set; }
        public decimal? DocOrderAmt { get; set; }
        public decimal? Rpt1OrderAmt { get; set; }
        public decimal? Rpt2OrderAmt { get; set; }
        public decimal? Rpt3OrderAmt { get; set; }
        public string? TaxRegionCode { get; set; }
        public decimal? TotalWHTax { get; set; }
        public decimal? DocTotalWHTax { get; set; }
        public decimal? Rpt1TotalWHTax { get; set; }
        public decimal? Rpt2TotalWHTax { get; set; }
        public decimal? Rpt3TotalWHTax { get; set; }
        public decimal? TotalSATax { get; set; }
        public decimal? DocTotalSATax { get; set; }
        public decimal? Rpt1TotalSATax { get; set; }
        public decimal? Rpt2TotalSATax { get; set; }
        public decimal? Rpt3TotalSATax { get; set; }
        public decimal? TotalTax { get; set; }
        public decimal? DocTotalTax { get; set; }
        public decimal? TotalDiscount { get; set; }
        public decimal? Rpt1TotalDiscount { get; set; }
        public decimal? Rpt2TotalDiscount { get; set; }
        public decimal? Rpt3TotalDiscount { get; set; }
        public decimal? DocTotalDiscount { get; set; }
        public decimal? ShipToCustNum { get; set; }
        public string? DeviceUOM { get; set; }
        public string? ManifestSizeUOM { get; set; }
        public string? ManifestWtUOM { get; set; }
        public decimal? ManifestWeight { get; set; }
        public decimal? ManifestLength { get; set; }
        public decimal? ManifestWidth { get; set; }
        public decimal? ManifestHeight { get; set; }
        public string? RateGrpCode { get; set; }
        public bool InPrice { get; set; }
        public bool PBHoldNoInv { get; set; }
        public decimal? ReconcileQty { get; set; }
        public string? ScheduleNumber { get; set; }
        public decimal? CounterASN { get; set; }
        public string? OurBank { get; set; }
        public bool ERSOrder { get; set; }
        public bool AutoPrintReady { get; set; }
        public bool ShipOvers { get; set; }
        public bool WIPackSlipCreated { get; set; }
        public string? AGAuthorizationCode { get; set; }
        public DateTime? AGAuthorizationDate { get; set; }
        public string? AGCarrierCUIT { get; set; }
        public bool AGCOTMark { get; set; }
        public string? AGDocumentLetter { get; set; }
        public string? AGInvoicingPoint { get; set; }
        public string? AGLegalNumber { get; set; }
        public string? AGPrintingControlType { get; set; }
        public string? AGTrackLicense { get; set; }
        public string? DispatchReason { get; set; }
        public string? AGShippingWay { get; set; }
        public string? OurSupplierCode { get; set; }
        public DateTime? ASNPrintedDate { get; set; }
        public string? EDIShipToNum { get; set; }
        public string? MXIncoterm { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string? DigitalSignature { get; set; }
        public DateTime? SignedOn { get; set; }
        public string? SignedBy { get; set; }
        public DateTime? FirstPrintDate { get; set; }
        public decimal? DocCopyNum { get; set; }
        public string? CNDeclarationBill { get; set; }
        public bool CNSample { get; set; }
        public bool CNBonded { get; set; }
        public DateTime? MXCertifiedTimestamp { get; set; }
        public string? MXCertificateSN { get; set; }
        public string? MXCertificate { get; set; }
        public string? MXFiscalFolio { get; set; }
        public string? MXSATCertificateSN { get; set; }
        public string? MXDigitalSeal { get; set; }
        public string? MXSATSeal { get; set; }
        public string? MXOriginalString { get; set; }
        public string? MXOriginalStringTFD { get; set; }
        public string? MXSerie { get; set; }
        public string? MXFolio { get; set; }
        public DateTime? MXETD { get; set; }
        public DateTime? MXETA { get; set; }
        public decimal? MXDistance { get; set; }
        public string? MXPermitType { get; set; }
        public string? MXPermitNum { get; set; }
        public string? MXCartaPorteStatus { get; set; }
        public string? VehicleLicensePlate { get; set; }
        public string? VehicleType { get; set; }
        public decimal? VehicleYear { get; set; }
        public string? DriverID { get; set; }
        public string? MXCancelFiscalFolio { get; set; }
        public string? AddrList { get; set; }
        public bool AllowChgAfterPrint { get; set; }
        public string? BillAddr { get; set; }
        public string? BTCustID { get; set; }
        public string? BTCustomerName { get; set; }
        public decimal? CartonContentValue { get; set; }
        public string? CartonStageNbr { get; set; }
        public DateTime? ChangeDateTime { get; set; }
        public string? CheckOrderMessage { get; set; }
        public string? CreditCardMessage { get; set; }
        public bool CreditHold { get; set; }
        public string? CtnPkgCode { get; set; }
        public bool DisplayInPrice { get; set; }
        public decimal? DocTaxAmt { get; set; }
        public decimal? DocWithholdingTaxAmt { get; set; }
        public bool DoPostUpdate { get; set; }
        public string? DspDigitalSignature { get; set; }
        public bool EnableAssignLegNum { get; set; }
        public bool EnablePackageControl { get; set; }
        public bool EnablePhantom { get; set; }
        public bool EnableShipped { get; set; }
        public bool EnableTax { get; set; }
        public bool EnableTranDocType { get; set; }
        public bool EnableVoidLegNum { get; set; }
        public bool EnableWeight { get; set; }
        public bool FromMasterPack { get; set; }
        public bool HasCartonLines { get; set; }
        public bool HasLegNumCnfg { get; set; }
        public bool LastCartonFlag { get; set; }
        public string? LegalNumberMessage { get; set; }
        public bool ManifestFlag { get; set; }
        public decimal? MasterpackPackNum { get; set; }
        public bool MultipleShippers { get; set; }
        public DateTime? OrderDate { get; set; }
        public bool OrderHold { get; set; }
        public decimal? OrderNum { get; set; }
        public string? PCID { get; set; }
        public bool PhantomCasesExist { get; set; }
        public decimal? PkgHeightEnable { get; set; }
        public decimal? PkgLenEnable { get; set; }
        public decimal? PkgSizeUOMEnable { get; set; }
        public decimal? PkgWidthEnable { get; set; }
        public string? PostUpdMessage { get; set; }
        public bool QSUseBOL { get; set; }
        public bool QSUseCO { get; set; }
        public bool QSUseIntl { get; set; }
        public bool ReadyToInvoiceChanged { get; set; }
        public decimal? ReplicateCount { get; set; }
        public decimal? Rpt1TaxAmt { get; set; }
        public decimal? Rpt2TaxAmt { get; set; }
        public decimal? Rpt3TaxAmt { get; set; }
        public bool SendShipment { get; set; }
        public string? ShipToNumName { get; set; }
        public string? SlipStatus { get; set; }
        public bool StageShipped { get; set; }
        public bool StagingReq { get; set; }
        public string? StatusChgMessage { get; set; }
        public decimal? TaxAmt { get; set; }
        public string? AutoInvoiceMessage { get; set; }
        public string? ShipToAddressFormatted { get; set; }
        public string? SoldToAddressFormatted { get; set; }
        public DateTime? MXETADate { get; set; }
        public decimal? MXETATime { get; set; }
        public DateTime? MXETDDate { get; set; }
        public decimal? MXETDTime { get; set; }
        public decimal? BitFlag { get; set; }
        public string? AGInvoicingPointDescription { get; set; }
        public bool BTCustNumInactive { get; set; }
        public string? CurrencyCodeCurrSymbol { get; set; }
        public string? CurrencyCodeCurrDesc { get; set; }
        public string? CurrencyCodeCurrencyID { get; set; }
        public string? CurrencyCodeDocumentDesc { get; set; }
        public string? CurrencyCodeCurrName { get; set; }
        public bool CustomerSendToFSA { get; set; }
        public bool CustomerInactive { get; set; }
        public string? CustomerBTName { get; set; }
        public string? CustomerCustID { get; set; }
        public string? CustomerName { get; set; }
        public string? DeliveryTypeDescription { get; set; }
        public string? FreightedShipViaCodeDescription { get; set; }
        public string? FreightedShipViaCodeWebDesc { get; set; }
        public string? OurBankBankName { get; set; }
        public string? OurBankDescription { get; set; }
        public bool ShipToCustInactive { get; set; }
        public string? ShipToCustBTName { get; set; }
        public string? ShipToCustCustID { get; set; }
        public string? ShipToCustName { get; set; }
        public string? ShipViaCodeDescription { get; set; }
        public string? ShipViaCodeWebDesc { get; set; }
        public string? TaxRegionDescription { get; set; }
        public string? TranDocTypeDescription { get; set; }
        public string? RowMod { get; set; }
        public string? UD_SysRevID { get; set; }
        public string? PbsId_c { get; set; }
        public string? PbsCustomerComments_c { get; set; }
        public string? pbsType1_c { get; set; }
        public decimal? pbsQuantity1_c { get; set; }
        public string? pbsType2_c { get; set; }
        public decimal? pbsQuantity2_c { get; set; }
        public string? pbsType3_c { get; set; }
        public decimal? pbsQuantity3_c { get; set; }
        public string? pbsType4_c { get; set; }
        public decimal? pbsQuantity4_c { get; set; }
        public string? pbsType5_c { get; set; }
        public decimal? pbsQuantity5_c { get; set; }
        public string? pbsNotes_c { get; set; }
        public decimal? pbsLastLineChanged_c { get; set; }
        public string? pbsCustomPCID_c { get; set; }
        public decimal? PbsJourneyNum_c { get; set; }
        public List<ShipDtl>? ShipDtls { get; set; }
    }

    public class ShipDtl
    {
        public string? Company { get; set; }
        public int? PackNum { get; set; }
        public decimal? PackLine { get; set; }
        public decimal? OrderNum { get; set; }
        public decimal? OrderLine { get; set; }
        public decimal? OrderRelNum { get; set; }
        public string? LineType { get; set; }
        public decimal? OurInventoryShipQty { get; set; }
        public decimal? OurJobShipQty { get; set; }
        public string? JobNum { get; set; }
        public decimal? Packages { get; set; }
        public string? PartNum { get; set; }
        public string? LineDesc { get; set; }
        public string? IUM { get; set; }
        public string? RevisionNum { get; set; }
        public string? ShipComment { get; set; }
        public bool ShipCmpl { get; set; }
        public string? WarehouseCode { get; set; }
        public string? BinNum { get; set; }
        public bool UpdatedInventory { get; set; }
        public string? XPartNum { get; set; }
        public string? XRevisionNum { get; set; }
        public decimal? ShpConNum { get; set; }
        public bool TMBilling { get; set; }
        public bool Invoiced { get; set; }
        public string? WUM { get; set; }
        public string? LotNum { get; set; }
        public string? DimCode { get; set; }
        public string? DUM { get; set; }
        public decimal? DimConvFactor { get; set; }
        public string? InvoiceComment { get; set; }
        public string? WarrantyCode { get; set; }
        public decimal? CustNum { get; set; }
        public string? ShipToNum { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public decimal? MaterialDuration { get; set; }
        public decimal? LaborDuration { get; set; }
        public decimal? MiscDuration { get; set; }
        public string? MaterialMod { get; set; }
        public string? LaborMod { get; set; }
        public string? MiscMod { get; set; }
        public DateTime? MaterialExpiration { get; set; }
        public DateTime? LaborExpiration { get; set; }
        public DateTime? MiscExpiration { get; set; }
        public DateTime? LastExpiration { get; set; }
        public string? WarrantyComment { get; set; }
        public decimal? ContractNum { get; set; }
        public string? ContractCode { get; set; }
        public bool Onsite { get; set; }
        public bool MatCovered { get; set; }
        public bool LabCovered { get; set; }
        public bool MiscCovered { get; set; }
        public string? Plant { get; set; }
        public bool ReadyToInvoice { get; set; }
        public decimal? SellingInventoryShipQty { get; set; }
        public decimal? SellingJobShipQty { get; set; }
        public decimal? SellingFactor { get; set; }
        public string? SalesUM { get; set; }
        public decimal? TotalNetWeight { get; set; }
        public string? WIPWarehouseCode { get; set; }
        public string? WIPBinNum { get; set; }
        public string? SellingFactorDirection { get; set; }
        public string? HeaderShipComment { get; set; }
        public decimal? KitParentLine { get; set; }
        public string? ChangedBy { get; set; }
        public DateTime? ChangeDate { get; set; }
        public decimal? ChangeTime { get; set; }
        public string? InventoryShipUOM { get; set; }
        public string? JobShipUOM { get; set; }
        public bool TrackSerialNum { get; set; }
        public string? JobLotNum { get; set; }
        public string? BinType { get; set; }
        public bool NotCompliant { get; set; }
        public string? ComplianceMsg { get; set; }
        public decimal? DiscountPercent { get; set; }
        public string? PricePerCode { get; set; }
        public decimal? Discount { get; set; }
        public decimal? DocDiscount { get; set; }
        public decimal? Rpt1Discount { get; set; }
        public decimal? Rpt2Discount { get; set; }
        public decimal? Rpt3Discount { get; set; }
        public decimal? ExtPrice { get; set; }
        public decimal? DocExtPrice { get; set; }
        public decimal? Rpt1ExtPrice { get; set; }
        public decimal? Rpt2ExtPrice { get; set; }
        public decimal? Rpt3ExtPrice { get; set; }
        public decimal? UnitPrice { get; set; }
        public decimal? DocUnitPrice { get; set; }
        public decimal? Rpt1UnitPrice { get; set; }
        public decimal? Rpt2UnitPrice { get; set; }
        public decimal? Rpt3UnitPrice { get; set; }
        public decimal? PickedAutoAllocatedQty { get; set; }
        public decimal? ShipToCustNum { get; set; }
        public decimal? InDiscount { get; set; }
        public decimal? DocInDiscount { get; set; }
        public decimal? Rpt1InDiscount { get; set; }
        public decimal? Rpt2InDiscount { get; set; }
        public decimal? Rpt3InDiscount { get; set; }
        public decimal? InExtPrice { get; set; }
        public decimal? DocInExtPrice { get; set; }
        public decimal? Rpt1InExtPrice { get; set; }
        public decimal? Rpt2InExtPrice { get; set; }
        public decimal? Rpt3InExtPrice { get; set; }
        public decimal? InUnitPrice { get; set; }
        public decimal? DocInUnitPrice { get; set; }
        public decimal? Rpt1InUnitPrice { get; set; }
        public decimal? Rpt2InUnitPrice { get; set; }
        public decimal? Rpt3InUnitPrice { get; set; }
        public bool InPrice { get; set; }
        public decimal? MFCustNum { get; set; }
        public string? MFShipToNum { get; set; }
        public bool UseOTMF { get; set; }
        public string? OTMFName { get; set; }
        public string? OTMFAddress1 { get; set; }
        public string? OTMFAddress2 { get; set; }
        public string? OTMFAddress3 { get; set; }
        public string? OTMFCity { get; set; }
        public string? OTMFState { get; set; }
        public string? OTMFZIP { get; set; }
        public string? OTMFContact { get; set; }
        public string? OTMFFaxNum { get; set; }
        public string? OTMFPhoneNum { get; set; }
        public decimal? OTMFCountryNum { get; set; }
        public decimal? RenewalNbr { get; set; }
        public bool ShipOvers { get; set; }
        public decimal? AllowedOvers { get; set; }
        public decimal? AllowedUnders { get; set; }
        public decimal? SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public decimal? NotAllocatedQty { get; set; }
        public string? PCID { get; set; }
        public decimal? PCIDItemSeq { get; set; }
        public string? DockingStation { get; set; }
        public bool UseShipDtlInfo { get; set; }
        public string? PkgCodePartNum { get; set; }
        public string? CustContainerPartNum { get; set; }
        public string? LabelType { get; set; }
        public bool WarrantySendToFSA { get; set; }
        public bool FSAEquipment { get; set; }
        public decimal? AttributeSetID { get; set; }
        public decimal? InventoryNumberOfPieces { get; set; }
        public decimal? JobNumberOfPieces { get; set; }
        public decimal? MXEstValue { get; set; }
        public string? MXEstValueCurrencyCode { get; set; }
        public bool MXHazardousShipment { get; set; }
        public string? MXHazardousType { get; set; }
        public string? MXPackageType { get; set; }
        public decimal? CNDeclarationBillLine { get; set; }
        public decimal? JobNotAllocatedQty { get; set; }
        public decimal? JobPickedAutoAllocatedQty { get; set; }
        public bool BuyToOrder { get; set; }
        public DateTime? ChangeDateTime { get; set; }
        public string? CurrencyCode { get; set; }
        public string? DimCodeList { get; set; }
        public decimal? DisplayInvQty { get; set; }
        public decimal? DocLineTax { get; set; }
        public bool DropShip { get; set; }
        public bool DtlError { get; set; }
        public bool EnableInvIDBtn { get; set; }
        public bool EnableInvSerialBtn { get; set; }
        public bool EnableJobFields { get; set; }
        public bool EnableKitIDBtn { get; set; }
        public bool EnableMfgIDBtn { get; set; }
        public bool EnableMfgSerialBtn { get; set; }
        public bool EnableOBInvSerialBtn { get; set; }
        public bool EnableOBMfgSerialBtn { get; set; }
        public bool EnablePackageControl { get; set; }
        public bool EnablePOSerialBtn { get; set; }
        public string? ExtJobNum { get; set; }
        public decimal? FSAInstallationCost { get; set; }
        public decimal? FSAInstallationOrderLine { get; set; }
        public decimal? FSAInstallationOrderNum { get; set; }
        public bool FSAInstallationRequired { get; set; }
        public string? FSAInstallationType { get; set; }
        public bool GetLocIDNum { get; set; }
        public string? InvLegalNumber { get; set; }
        public decimal? InvoiceNum { get; set; }
        public bool KitBackFlush { get; set; }
        public string? KitBinNum { get; set; }
        public bool KitCompIssue { get; set; }
        public bool KitCompShipComplete { get; set; }
        public string? KitDescription { get; set; }
        public string? KitFlag { get; set; }
        public string? KitIUM { get; set; }
        public string? KitLotNum { get; set; }
        public bool KitMassIssue { get; set; }
        public bool KitParentIssue { get; set; }
        public string? KitPartNum { get; set; }
        public decimal? KitQtyFromInv { get; set; }
        public bool KitQtyFromInvEnabled { get; set; }
        public bool KitSerialTracked { get; set; }
        public bool KitTrackLots { get; set; }
        public string? KitWarehouse { get; set; }
        public string? KitWarehouseCodeDesc { get; set; }
        public string? KitWhseList { get; set; }
        public string? LegalNumber { get; set; }
        public decimal? LineContentValue { get; set; }
        public decimal? LineTax { get; set; }
        public string? LinkMsg { get; set; }
        public string? MarkForAddrList { get; set; }
        public string? MFCustID { get; set; }
        public bool OrderHold { get; set; }
        public decimal? OrderRelOurReqQty { get; set; }
        public string? OurJobShipIUM { get; set; }
        public decimal? OurJobShippedQty { get; set; }
        public decimal? OurRemainQty { get; set; }
        public string? OurRemainUM { get; set; }
        public decimal? OurReqQty { get; set; }
        public string? OurReqUM { get; set; }
        public decimal? OurShippedQty { get; set; }
        public string? OurShippedUM { get; set; }
        public decimal? OurStockShippedQty { get; set; }
        public string? PackSlip { get; set; }
        public string? PartAESExp { get; set; }
        public string? PartCompany { get; set; }
        public string? PartECNNumber { get; set; }
        public string? PartExpLicNumber { get; set; }
        public string? PartExpLicType { get; set; }
        public string? PartHazClass { get; set; }
        public string? PartHazGvrnmtID { get; set; }
        public bool PartHazItem { get; set; }
        public string? PartHazPackInstr { get; set; }
        public string? PartHazSub { get; set; }
        public string? PartHazTechName { get; set; }
        public string? PartHTS { get; set; }
        public string? PartNAFTAOrigCountry { get; set; }
        public string? PartNAFTAPref { get; set; }
        public string? PartNAFTAProd { get; set; }
        public string? PartOrigCountry { get; set; }
        public string? PartPartNum { get; set; }
        public string? PartSchedBcode { get; set; }
        public bool PartUseHTSDesc { get; set; }
        public string? PONum { get; set; }
        public string? ProjectID { get; set; }
        public string? PurPoint { get; set; }
        public DateTime? RequestDate { get; set; }
        public decimal? Rpt1LineTax { get; set; }
        public decimal? Rpt2LineTax { get; set; }
        public decimal? Rpt3LineTax { get; set; }
        public decimal? SelectedLocationIDQty { get; set; }
        public decimal? SellingRemainQty { get; set; }
        public string? SellingRemainUM { get; set; }
        public decimal? SellingReqQty { get; set; }
        public string? SellingReqUM { get; set; }
        public decimal? SellingShipmentQty { get; set; }
        public string? SellingShipmentUM { get; set; }
        public decimal? SellingShippedQty { get; set; }
        public string? SellingShippedUM { get; set; }
        public DateTime? ShipDate { get; set; }
        public string? ShipToWarning { get; set; }
        public string? ShipViaCode { get; set; }
        public bool StockPart { get; set; }
        public bool TrackID { get; set; }
        public decimal? TranLocationIDQty { get; set; }
        public decimal? VendorNum { get; set; }
        public string? WhseList { get; set; }
        public decimal? KitAttributeSetID { get; set; }
        public string? AttributeSetDescription { get; set; }
        public string? AttributeSetShortDescription { get; set; }
        public string? KitAttributeSetDescription { get; set; }
        public string? KitAttributeSetShortDescription { get; set; }
        public string? KitPartAttrClassID { get; set; }
        public bool EnableAttributeSetSearch { get; set; }
        public string? MarkForAddrFormatted { get; set; }
        public decimal? DispInventoryNumberOfPieces { get; set; }
        public decimal? DispJobNumberOfPieces { get; set; }
        public string? KitRevisionNum { get; set; }
        public string? CNDeclarationBill { get; set; }
        public decimal? BitFlag { get; set; }
        public string? BinNumDescription { get; set; }
        public string? ContractCodeContractDescription { get; set; }
        public bool CustNumSendToFSA { get; set; }
        public string? CustNumName { get; set; }
        public string? CustNumCustID { get; set; }
        public string? CustNumBTName { get; set; }
        public string? DimensionDimCodeDescription { get; set; }
        public string? JobNumPartDescription { get; set; }
        public string? LotPartLotDescription { get; set; }
        public string? OrderLineProdCode { get; set; }
        public string? OrderLineLineDesc { get; set; }
        public string? OrderNumPSCurrCode { get; set; }
        public string? OrderNumCardMemberName { get; set; }
        public string? OrderNumCurrencyCode { get; set; }
        public string? OTMFCountryDescription { get; set; }
        public bool PackNumUseOTS { get; set; }
        public string? PackNumShipStatus { get; set; }
        public bool PartNumTrackInventoryByRevision { get; set; }
        public string? PartNumAttrClassID { get; set; }
        public bool PartNumSendToFSA { get; set; }
        public bool PartNumTrackSerialNum { get; set; }
        public string? PartNumPricePerCode { get; set; }
        public decimal? PartNumSellingFactor { get; set; }
        public string? PartNumSalesUM { get; set; }
        public string? PartNumIUM { get; set; }
        public bool PartNumTrackLots { get; set; }
        public bool PartNumTrackDimension { get; set; }
        public string? PartNumPartDescription { get; set; }
        public string? PartNumWarrantyCode { get; set; }
        public bool PartNumFSAEquipment { get; set; }
        public bool PartNumTrackInventoryAttributes { get; set; }
        public string? PlantName { get; set; }
        public string? WarehouseCodeDescription { get; set; }
        public bool WarrantyCodeSendToFSA { get; set; }
        public string? WarrantyCodeWarrDescription { get; set; }
        public string? WIPWarehouseCodeDescription { get; set; }
        public string? RowMod { get; set; }
        public string? UD_SysRevID { get; set; }
        public decimal? PbsId_c { get; set; }
    }


}
