// ReSharper disable InconsistentNaming
namespace KairosWebAPI.Models.Dto
{
    public class SalesOrder
    {
        //public bool OpenOrder { get; set; }
        ////public bool VoidOrder { get; set; }
        public string? Company { get; set; }
        //public decimal? OrderNum { get; set; }
        public decimal? CustNum { get; set; }
        public string? CustomerCustID { get; set; }
        public string? PONum { get; set; }
        public DateTime? RequestDate { get; set; }
        public DateTime? OrderDate { get; set; }
        public DateTime? NeedByDate { get; set; }
        public bool UseOTS { get; set; }
        public string? OTSName { get; set; }
        public string? OTSAddress1 { get; set; }
        public string? OTSAddress2 { get; set; }
        public string? OTSCity { get; set; }
        public string? OTSState { get; set; }
        public string? OTSZIP { get; set; }
        public string? TermsCode { get; set; }

        public List<OrderDtl>? OrderDtls { get; set; }
        //public bool OrderHeld { get; set; }
        public string? EntryPerson { get; set; }
        //public string? ShipToNum { get; set; }
        //public string? FOB { get; set; }
        //public string? ShipViaCode { get; set; }
        //public string? TermsCode { get; set; }
        //public decimal? DiscountPercent { get; set; }
        //public decimal? PrcConNum { get; set; }
        //public decimal? ShpConNum { get; set; }
        //public string? SalesRepList { get; set; }
        //public string? OrderComment { get; set; }
        //public string? ShipComment { get; set; }
        //public string? InvoiceComment { get; set; }
        //public string? PickListComment { get; set; }
        //public decimal? DepositBal { get; set; }
        //public decimal? DocDepositBal { get; set; }

        //public bool CreditOverride { get; set; }
        //public string? CreditOverrideUserID { get; set; }
        //public DateTime? CreditOverrideDate { get; set; }
        //public string? CreditOverrideTime { get; set; }
        //public decimal? CreditOverrideLimit { get; set; }
        //public bool SndAlrtShp { get; set; }
        //public decimal? ExchangeRate { get; set; }
        //public string? CurrencyCode { get; set; }
        //public bool LockRate { get; set; }
        //public string? CardMemberName { get; set; }
        //public string? CardNumber { get; set; }
        //public string? CardType { get; set; }
        //public decimal? ExpirationMonth { get; set; }
        //public decimal? ExpirationYear { get; set; }
        //public string? CardID { get; set; }
        //public string? CardmemberReference { get; set; }
        //public string? AllocPriorityCode { get; set; }
        //public string? ReservePriorityCode { get; set; }
        //public bool ShipOrderComplete { get; set; }
        //public bool WebOrder { get; set; }
        //public string? CCApprovalNum { get; set; }
        //public bool EDIOrder { get; set; }
        //public bool EDIAck { get; set; }
        //public bool Linked { get; set; }
        //public decimal? ICPONum { get; set; }
        //public string? ExtCompany { get; set; }
        //public string? WebEntryPerson { get; set; }
        //public bool AckEmailSent { get; set; }
        //public bool ApplyOrderBasedDisc { get; set; }
        //public bool AutoOrderBasedDisc { get; set; }
        //public string? EntryMethod { get; set; }
        //public decimal? HDCaseNum { get; set; }
        //public bool CounterSale { get; set; }
        //public bool CreateInvoice { get; set; }
        //public bool CreatePackingSlip { get; set; }
        //public bool LockQty { get; set; }
        //public string? ProcessCard { get; set; }
        //public decimal? CCAmount { get; set; }
        //public decimal? CCFreight { get; set; }
        //public decimal? CCTax { get; set; }
        //public decimal? CCTotal { get; set; }
        //public decimal? CCDocAmount { get; set; }
        //public decimal? CCDocFreight { get; set; }
        //public decimal? CCDocTax { get; set; }
        //public decimal? CCDocTotal { get; set; }
        //public string? CCStreetAddr { get; set; }
        //public string? CCZip { get; set; }
        //public decimal? BTCustNum { get; set; }
        //public decimal? BTConNum { get; set; }
        //public decimal? RepRate4 { get; set; }
        //public decimal? RepRate5 { get; set; }
        //public decimal? RepSplit1 { get; set; }
        //public decimal? RepSplit2 { get; set; }
        //public decimal? RepSplit3 { get; set; }
        //public decimal? RepSplit4 { get; set; }
        //public decimal? RepSplit5 { get; set; }
        //public decimal? RepRate1 { get; set; }
        //public decimal? RepRate2 { get; set; }
        //public decimal? RepRate3 { get; set; }
        //public decimal? OutboundSalesDocCtr { get; set; }
        //public decimal? OutboundShipDocsCtr { get; set; }
        //public decimal? DemandContractNum { get; set; }
        //public DateTime? DoNotShipBeforeDate { get; set; }
        //public bool ResDelivery { get; set; }
        //public DateTime? DoNotShipAfterDate { get; set; }
        //public bool SatDelivery { get; set; }
        //public bool SatPickup { get; set; }
        //public bool Hazmat { get; set; }
        //public bool DocOnly { get; set; }
        //public string? RefNotes { get; set; }
        //public bool ApplyChrg { get; set; }
        //public decimal? ChrgAmount { get; set; }
        //public bool COD { get; set; }
        //public bool CODFreight { get; set; }
        //public bool CODCheck { get; set; }
        //public decimal? CODAmount { get; set; }
        //public string? GroundType { get; set; }
        //public bool NotifyFlag { get; set; }
        //public string? NotifyEMail { get; set; }
        //public bool DeclaredIns { get; set; }
        //public decimal? DeclaredAmt { get; set; }
        //public DateTime? CancelAfterDate { get; set; }
        //public bool DemandRejected { get; set; }
        //public bool OverrideCarrier { get; set; }
        //public bool OverrideService { get; set; }
        //public bool CreditCardOrder { get; set; }
        //public decimal? DemandHeadSeq { get; set; }
        //public string? PayFlag { get; set; }
        //public string? PayAccount { get; set; }
        //public string? PayBTAddress1 { get; set; }
        //public string? PayBTAddress2 { get; set; }
        //public string? PayBTCity { get; set; }
        //public string? PayBTState { get; set; }
        //public string? PayBTZip { get; set; }
        //public string? PayBTCountry { get; set; }
        //public bool DropShip { get; set; }
        //public bool CommercialInvoice { get; set; }
        //public bool ShipExprtDeclartn { get; set; }
        //public bool CertOfOrigin { get; set; }
        //public bool LetterOfInstr { get; set; }
        //public string? FFID { get; set; }
        //public string? FFAddress1 { get; set; }
        //public string? FFAddress2 { get; set; }
        //public string? FFCity { get; set; }
        //public string? FFState { get; set; }
        //public string? FFZip { get; set; }
        //public string? FFCountry { get; set; }
        //public string? FFContact { get; set; }
        //public string? FFCompName { get; set; }
        //public string? FFPhoneNum { get; set; }
        //public bool IntrntlShip { get; set; }
        //public string? ChangedBy { get; set; }
        //public DateTime? ChangeDate { get; set; }
        //public decimal? ChangeTime { get; set; }
        //public bool AutoPrintReady { get; set; }
        //public bool EDIReady { get; set; }
        //public bool IndividualPackIDs { get; set; }
        //public string? FFAddress3 { get; set; }
        //public decimal? DeliveryConf { get; set; }
        //public bool AddlHdlgFlag { get; set; }
        //public bool NonStdPkg { get; set; }
        //public bool ServSignature { get; set; }
        //public bool ServAlert { get; set; }
        //public bool ServHomeDel { get; set; }
        //public string? DeliveryType { get; set; }
        //public DateTime? ServDeliveryDate { get; set; }
        //public string? ServInstruct { get; set; }
        //public string? ServRef1 { get; set; }
        //public string? ServRef2 { get; set; }
        //public string? ServRef3 { get; set; }
        //public string? ServRef4 { get; set; }
        //public string? ServRef5 { get; set; }
        //public decimal? FFCountryNum { get; set; }
        //public string? ServPhone { get; set; }
        //public bool ServRelease { get; set; }
        //public string? ServAuthNum { get; set; }
        //public string? PayBTAddress3 { get; set; }
        //public decimal? PayBTCountryNum { get; set; }
        //public string? PayBTPhone { get; set; }
        //public bool UPSQuantumView { get; set; }
        //public string? UPSQVShipFromName { get; set; }
        //public string? UPSQVMemo { get; set; }
        //public bool ReadyToCalc { get; set; }
        //public decimal? TotalCharges { get; set; }
        //public decimal? TotalMisc { get; set; }
        //public decimal? TotalDiscount { get; set; }
        //public decimal? TotalComm { get; set; }
        //public decimal? TotalAdvBill { get; set; }
        //public decimal? TotalLines { get; set; }
        //public decimal? TotalReleases { get; set; }
        //public decimal? TotalRelDates { get; set; }
        //public decimal? DocTotalCharges { get; set; }
        //public decimal? DocTotalMisc { get; set; }
        //public decimal? DocTotalDiscount { get; set; }
        //public decimal? DocTotalComm { get; set; }
        //public decimal? TotalTax { get; set; }
        //public decimal? DocTotalTax { get; set; }
        //public decimal? DocTotalAdvBill { get; set; }
        //public decimal? TotalShipped { get; set; }
        //public decimal? TotalInvoiced { get; set; }
        //public decimal? TotalCommLines { get; set; }
        //public decimal? SRCommAmt1 { get; set; }
        //public decimal? SRCommAmt2 { get; set; }
        //public decimal? SRCommAmt3 { get; set; }
        //public decimal? SRCommAmt4 { get; set; }
        //public decimal? SRCommAmt5 { get; set; }
        //public decimal? SRCommableAmt1 { get; set; }
        //public decimal? SRCommableAmt2 { get; set; }
        //public decimal? SRCommableAmt3 { get; set; }
        //public decimal? SRCommableAmt4 { get; set; }
        //public decimal? SRCommableAmt5 { get; set; }
        //public decimal? Rounding { get; set; }
        //public decimal? Rpt1DepositBal { get; set; }
        //public decimal? DocRounding { get; set; }
        //public decimal? Rpt2DepositBal { get; set; }
        //public decimal? Rpt3DepositBal { get; set; }
        //public decimal? Rpt1TotalCharges { get; set; }
        //public decimal? Rpt2TotalCharges { get; set; }
        //public decimal? Rpt3TotalCharges { get; set; }
        //public decimal? Rpt1TotalAdvBill { get; set; }
        //public decimal? Rpt2TotalAdvBill { get; set; }
        //public decimal? Rpt3TotalAdvBill { get; set; }
        //public decimal? Rpt1TotalMisc { get; set; }
        //public decimal? Rpt2TotalMisc { get; set; }
        //public decimal? Rpt3TotalMisc { get; set; }
        //public decimal? Rpt1TotalDiscount { get; set; }
        //public decimal? Rpt2TotalDiscount { get; set; }
        //public decimal? Rpt3TotalDiscount { get; set; }
        //public decimal? Rpt1TotalComm { get; set; }
        //public decimal? Rpt2TotalComm { get; set; }
        //public decimal? Rpt3TotalComm { get; set; }
        //public decimal? Rpt1TotalTax { get; set; }
        //public decimal? Rpt2TotalTax { get; set; }
        //public decimal? Rpt1Rounding { get; set; }
        //public decimal? Rpt2Rounding { get; set; }
        //public decimal? Rpt3Rounding { get; set; }
        //public string? RateGrpCode { get; set; }
        //public decimal? Rpt3TotalTax { get; set; }
        //public decimal? Rpt1CCAmount { get; set; }
        //public decimal? Rpt2CCAmount { get; set; }
        //public decimal? Rpt3CCAmount { get; set; }
        //public decimal? Rpt1CCFreight { get; set; }
        //public decimal? Rpt2CCFreight { get; set; }
        //public decimal? Rpt3CCFreight { get; set; }
        //public decimal? Rpt1CCTax { get; set; }
        //public decimal? Rpt2CCTax { get; set; }
        //public decimal? Rpt3CCTax { get; set; }
        //public decimal? Rpt1CCTotal { get; set; }
        //public decimal? Rpt2CCTotal { get; set; }
        //public decimal? Rpt3CCTotal { get; set; }
        //public decimal? OrderAmt { get; set; }
        //public decimal? DocOrderAmt { get; set; }
        //public decimal? Rpt1OrderAmt { get; set; }
        //public decimal? Rpt2OrderAmt { get; set; }
        //public decimal? Rpt3OrderAmt { get; set; }
        //public DateTime? TaxPoint { get; set; }
        //public DateTime? TaxRateDate { get; set; }
        //public string? TaxRegionCode { get; set; }
        //public string? OTSAddress3 { get; set; }

        //public string? OTSResaleID { get; set; }
        //public string? OTSContact { get; set; }
        //public string? OTSFaxNum { get; set; }
        //public string? OTSPhoneNum { get; set; }
        //public decimal? OTSCountryNum { get; set; }
        //public decimal? TotalWHTax { get; set; }
        //public decimal? DocTotalWHTax { get; set; }
        //public decimal? Rpt1TotalWHTax { get; set; }
        //public decimal? Rpt2TotalWHTax { get; set; }
        //public decimal? Rpt3TotalWHTax { get; set; }
        //public decimal? TotalSATax { get; set; }
        //public decimal? DocTotalSATax { get; set; }
        //public decimal? Rpt1TotalSATax { get; set; }
        //public decimal? Rpt2TotalSATax { get; set; }
        //public decimal? Rpt3TotalSATax { get; set; }
        //public string? OTSSaveAs { get; set; }
        //public string? OTSSaveCustID { get; set; }
        //public bool OTSCustSaved { get; set; }
        //public decimal? ShipToCustNum { get; set; }
        //public string? OrderStatus { get; set; }
        //public bool HoldSetByDemand { get; set; }
        //public bool InPrice { get; set; }
        //public decimal? InTotalCharges { get; set; }
        //public decimal? InTotalMisc { get; set; }
        //public decimal? InTotalDiscount { get; set; }
        //public decimal? DocInTotalCharges { get; set; }
        //public decimal? DocInTotalMisc { get; set; }
        //public decimal? DocInTotalDiscount { get; set; }
        //public decimal? Rpt1InTotalCharges { get; set; }
        //public decimal? Rpt2InTotalCharges { get; set; }
        //public decimal? Rpt3InTotalCharges { get; set; }
        //public decimal? Rpt1InTotalMisc { get; set; }
        //public decimal? Rpt2InTotalMisc { get; set; }
        //public decimal? Rpt3InTotalMisc { get; set; }
        //public decimal? Rpt1InTotalDiscount { get; set; }
        //public decimal? Rpt2InTotalDiscount { get; set; }
        //public decimal? Rpt3InTotalDiscount { get; set; }
        //public string? ARLOCID { get; set; }
        //public string? OurBank { get; set; }
        //public bool ERSOrder { get; set; }
        //public bool LOCHold { get; set; }
        //public string? PSCurrCode { get; set; }
        //public string? InvCurrCode { get; set; }
        //public string? LegalNumber { get; set; }
        //public string? TranDocTypeID { get; set; }
        //public string? XRefContractNum { get; set; }
        //public DateTime? XRefContractDate { get; set; }
        //public DateTime? DemandProcessDate { get; set; }
        //public decimal? DemandProcessTime { get; set; }
        //public string? LastScheduleNumber { get; set; }
        //public string? LastTCtrlNum { get; set; }
        //public string? LastBatchNum { get; set; }
        //public string? ECCOrderNum { get; set; }
        //public string? ECCPONum { get; set; }
        //public string? WIOrder { get; set; }
        //public string? WIApplication { get; set; }
        //public string? WIUsername { get; set; }
        //public string? WIUserID { get; set; }
        //public bool WICreditCardorder { get; set; }
        //public string? OrderCSR { get; set; }
        //public string? UserChar1 { get; set; }
        //public string? UserChar2 { get; set; }
        //public string? UserChar3 { get; set; }
        //public string? UserChar4 { get; set; }
        //public DateTime? UserDate1 { get; set; }
        //public DateTime? UserDate2 { get; set; }
        //public DateTime? UserDate3 { get; set; }
        //public DateTime? UserDate4 { get; set; }
        //public decimal? UserDecimal1 { get; set; }
        //public decimal? UserDecimal2 { get; set; }
        //public decimal? UserInteger1 { get; set; }
        //public decimal? UserInteger2 { get; set; }
        //public decimal? SysRevID { get; set; }
        //public string? SysRowID { get; set; }
        //public bool IsCSRSet { get; set; }
        //public string? ECCPaymentMethod { get; set; }
        //public bool AGUseGoodDefaultMark { get; set; }
        //public string? OTSShipToNum { get; set; }
        //public string? ProFormaInvComment { get; set; }
        //public string? ccToken { get; set; }
        //public bool InvcOrderCmp { get; set; }
        //public bool ReprintSOAck { get; set; }
        //public decimal? CounterSOAck { get; set; }
        //public string? DispatchReason { get; set; }
        //public string? Plant { get; set; }
        //public bool ReadyToFulfill { get; set; }
        //public decimal? ShipByTime { get; set; }
        //public decimal? TWFiscalYear { get; set; }
        //public string? TWFiscalYearSuffix { get; set; }
        //public decimal? TWFiscalPeriod { get; set; }
        //public string? TWGUIGroup { get; set; }
        //public string? TWGUIRegNumSeller { get; set; }
        //public string? TWGUIRegNumBuyer { get; set; }
        //public decimal? OrderOpenCredit { get; set; }
        //public decimal? ClosedNotShipped { get; set; }
        //public decimal? InvCurrDepositBal { get; set; }
        //public bool PLArticle106c { get; set; }
        //public bool PLInvIssuedByTaxpayer { get; set; }
        //public bool PLInvIssuedBySecondTaxpayer { get; set; }
        //public bool PLTouristService { get; set; }
        //public bool PLSecondHandOrArts { get; set; }
        //public string? PLLegalArticleAct { get; set; }
        //public string? PLLegalArticleWEDirective { get; set; }
        //public string? PLLegalArticleOther { get; set; }
        //public string? PLEnforcementAuthName { get; set; }
        //public string? PLEnforcementAuthAddr { get; set; }
        //public string? PLTaxRepresentativeName { get; set; }
        //public string? PLTaxRepresentativeAddr { get; set; }
        //public string? PLTaxRepresentativeTaxID { get; set; }
        //public decimal? PLMarginScheme { get; set; }
        //public bool PLGoodsOrServiceVATExempt { get; set; }
        //public string? CCCity { get; set; }
        //public string? CCState { get; set; }
        //public string? ExtAOEUserID { get; set; }
        //public string? ExtAOE { get; set; }
        //public decimal? OTSTaxValidationStatus { get; set; }
        //public DateTime? OTSTaxValidationDate { get; set; }
        //public string? AvailBTCustList { get; set; }
        //public string? AVSAddr { get; set; }
        //public string? AVSZip { get; set; }
        //public string? BaseCurrencyID { get; set; }
        //public string? BaseCurrSymbol { get; set; }
        //public string? BillToCustomerName { get; set; }
        //public string? BTAddressList { get; set; }
        //public string? BTContactEMailAddress { get; set; }
        //public string? BTContactFaxNum { get; set; }
        //public string? BTContactName { get; set; }
        //public string? BTContactPhoneNum { get; set; }
        //public string? BTCustID { get; set; }
        //public bool CanChangeTaxLiab { get; set; }
        //public string? CardStore { get; set; }
        //public string? CCCSCID { get; set; }
        //public string? CCCSCIDToken { get; set; }
        //public bool CCIsTraining { get; set; }
        //public string? CCResponse { get; set; }
        //public decimal? CCRounding { get; set; }
        //public string? CCTranID { get; set; }
        //public string? CCTranType { get; set; }
        //public string? CSCResult { get; set; }
        //public bool CurrencySwitch { get; set; }
        //public bool CustAllowOTS { get; set; }
        //public bool CustomerPrintAck { get; set; }
        //public bool CustomerRequiresPO { get; set; }
        //public bool CustOnCreditHold { get; set; }
        //public string? CustTradePartnerName { get; set; }
        //public string? DemandContract { get; set; }
        //public decimal? DocCCRounding { get; set; }
        //public decimal? DocTotalNet { get; set; }
        //public decimal? DocTotalOrder { get; set; }
        //public string? dspBTCustID { get; set; }
        //public string? ECCEmail { get; set; }
        //public string? ECCPaymentDesc { get; set; }
        //public bool EnableCreditCard { get; set; }
        //public bool EnableJobWizard { get; set; }
        //public bool EnableSoldToID { get; set; }
        //public string? EntryProcess { get; set; }
        //public bool ERSOverride { get; set; }
        //public bool HasMiscCharges { get; set; }
        //public bool HasOrderLines { get; set; }
        //public string? IntExternalKey { get; set; }
        //public string? LinkMsg { get; set; }
        //public bool NoTaxRgnChange { get; set; }
        //public bool OTSSaved { get; set; }
        //public string? OTSTaxRegionCode { get; set; }
        //public decimal? ParentCustNum { get; set; }
        //public string? ProposedTaxRgn { get; set; }
        //public string? ReferencePNRef { get; set; }
        //public bool ResetBTCustAddr { get; set; }
        //public bool ResetRelTaxRgn { get; set; }
        //public decimal? Rpt1CCRounding { get; set; }
        //public decimal? Rpt1TotalNet { get; set; }
        //public decimal? Rpt2CCRounding { get; set; }
        //public decimal? Rpt2TotalNet { get; set; }
        //public decimal? Rpt3CCRounding { get; set; }
        //public decimal? Rpt3TotalNet { get; set; }
        //public string? SalesRepCode1 { get; set; }
        //public string? SalesRepCode2 { get; set; }
        //public string? SalesRepCode3 { get; set; }
        //public string? SalesRepCode4 { get; set; }
        //public string? SalesRepCode5 { get; set; }
        //public string? SalesRepName1 { get; set; }
        //public string? SalesRepName2 { get; set; }
        //public string? SalesRepName3 { get; set; }
        //public string? SalesRepName4 { get; set; }
        //public string? SalesRepName5 { get; set; }
        //public string? ShipToAddressList { get; set; }
        //public string? ShipToContactEMailAddress { get; set; }
        //public string? ShipToContactFaxNum { get; set; }
        //public string? ShipToContactName { get; set; }
        //public string? ShipToContactPhoneNum { get; set; }
        //public string? ShipToCustId { get; set; }
        //public bool ShowApplyOrderDiscountsControl { get; set; }
        //public string? SoldToAddressList { get; set; }
        //public string? SoldToContactEMailAddress { get; set; }
        //public string? SoldToContactFaxNum { get; set; }
        //public string? SoldToContactName { get; set; }
        //public string? SoldToContactPhoneNum { get; set; }
        //public string? TermsType { get; set; }
        //public decimal? TotalNet { get; set; }
        //public decimal? TotalOrder { get; set; }
        //public string? TranDocTypeDescr { get; set; }
        //public decimal? TrueDiscountPercent { get; set; }
        //public string? TWGenerationType { get; set; }
        //public bool UpdateDtlAndRelRecords { get; set; }
        //public bool InvoicesExist { get; set; }
        //public string? BTAddressFormatted { get; set; }
        //public string? ShipToAddressFormatted { get; set; }
        //public string? SoldToAddressFormatted { get; set; }
        //public DateTime? TranDate { get; set; }
        //public decimal? TranNum { get; set; }
        //public decimal? TranTime { get; set; }
        //public bool OrderRelNeedByDateNotNull { get; set; }
        //public bool InactiveCustomer { get; set; }
        //public bool EnableAllocationQueueActions { get; set; }
        //public decimal? BitFlag { get; set; }
        //public string? BTCustNumCustID { get; set; }
        //public string? BTCustNumName { get; set; }
        //public string? BTCustNumBTName { get; set; }
        //public string? CardTypeDescription { get; set; }
        //public string? CurrencyCodeCurrName { get; set; }
        //public string? CurrencyCodeCurrSymbol { get; set; }
        //public string? CurrencyCodeDocumentDesc { get; set; }
        //public string? CurrencyCodeCurrencyID { get; set; }
        //public string? CurrencyCodeCurrDesc { get; set; }
        //public string? CustomerBTName { get; set; }
        //public string? CustomerName { get; set; }
        //public bool CustomerAllowShipTo3 { get; set; }
        //public string? FOBDescription { get; set; }
        //public string? HDCaseDescription { get; set; }
        //public string? InvCurrCurrDesc { get; set; }
        //public string? OTSCntryISOCode { get; set; }
        //public string? OTSCntryDescription { get; set; }
        //public bool OTSCntryEUMember { get; set; }
        //public string? OurBankDescription { get; set; }
        //public string? OurBankBankName { get; set; }
        //public string? PlantName { get; set; }
        //public string? PSCurrCurrDesc { get; set; }
        //public string? RateGrpDescription { get; set; }
        //public string? ReservePriDescription { get; set; }
        //public bool ShipViaCodeInactive { get; set; }
        //public string? ShipViaCodeDescription { get; set; }
        //public string? ShipViaCodeWebDesc { get; set; }
        //public string? TaxRegionCodeDescription { get; set; }
        //public string? TermsCodeDescription { get; set; }
        //public string? RowMod { get; set; }
        //public string? UD_SysRevID { get; set; }
        //public string? PbsId_c { get; set; }
        //public string? PbsStage_c { get; set; }
        //public string? PbsCustomerComments_c { get; set; }
        //public string? pbsJobNum_c { get; set; }
        //public string? pbsLoadNumber_c { get; set; }
        //public string? PbsSORef_c { get; set; }
        //public string? PbsCustomerRef_c { get; set; }
        //public bool pbsWebOrder_c { get; set; }
        //public bool pbsModShipTo_c { get; set; }
        //public string? pbsContactName_c { get; set; }
        //public string? pbsAddress1_c { get; set; }
        //public string? pbsAddress2_c { get; set; }
        //public string? pbsAddress3_c { get; set; }
        //public string? pbsState_c { get; set; }
        //public string? pbsPostalCode_c { get; set; }
        //public string? pbsCountry_c { get; set; }
        //public string? pbsCity_c { get; set; }
        //public bool pbsConfirmOrder_c { get; set; }
        //public bool pbsOrderStatus_c { get; set; }
        //public string? pbsCollectorName_c { get; set; }
        //public decimal? SiteOnHandQty_c { get; set; }
        //public decimal? SiteAvailableQty_c { get; set; }
        //public string? pbsPlant_c { get; set; }
        //public DateTime? pbsEarlyShipDate_c { get; set; }
        //public decimal? pbsEarlyShipDays_c { get; set; }
        //public bool pbsDropShip_c { get; set; }
        //public decimal? pbsSubTotal_c { get; set; }
        //public decimal? pbsLOCCode_c { get; set; }
        //public string? GALPlant_c { get; set; }
        //public bool pbsUrgent_c { get; set; }
        //public string? pbsUrgentBuyer_c { get; set; }
        //public bool SendEmail_c { get; set; }
        //public string? EmailAddress_c { get; set; }
        //public List<OHOrderMsc>? OHOrderMscs { get; set; }

        //public List<OrderHedUP>? OrderHedUPS { get; set; }
        //public List<OrderRepComm>? OrderRepComms { get; set; }
        //public List<OrderSched>? OrderScheds { get; set; }
        //public List<OrderHedAttch>? OrderHedAttches { get; set; }
    }
    public class OrderDtl
    {
        //public bool VoidLine { get; set; }
        //public bool OpenLine { get; set; }
        public string? Company { get; set; }
        public string? PartNum { get; set; }
        //public decimal? OrderNum { get; set; }
        //public decimal? OrderLine { get; set; }
        public string? LineType { get; set; }
        public string? LineDesc { get; set; }
        public decimal? OrderQty { get; set; }
        //public DateTime? RequestDate { get; set; }

        //public string? Reference { get; set; }
        //public string? IUM { get; set; }
        //public string? RevisionNum { get; set; }
        //public string? POLine { get; set; }
        //public bool Commissionable { get; set; }
        //public decimal? DiscountPercent { get; set; }
        //public decimal? UnitPrice { get; set; }
        //public decimal? DocUnitPrice { get; set; }

        //public decimal? Discount { get; set; }
        //public decimal? DocDiscount { get; set; }
        //public string? ProdCode { get; set; }
        //public string? XPartNum { get; set; }
        //public string? XRevisionNum { get; set; }
        //public string? PricePerCode { get; set; }
        //public string? OrderComment { get; set; }
        //public string? ShipComment { get; set; }
        //public string? InvoiceComment { get; set; }
        //public string? PickListComment { get; set; }
        //public string? TaxCatID { get; set; }
        //public decimal? AdvanceBillBal { get; set; }
        //public decimal? DocAdvanceBillBal { get; set; }
        //public decimal? QuoteNum { get; set; }
        //public decimal? QuoteLine { get; set; }
        //public bool TMBilling { get; set; }
        //public string? OrigWhyNoTax { get; set; }
        //public DateTime? NeedByDate { get; set; }
        //public decimal? CustNum { get; set; }
        //public bool Rework { get; set; }
        //public decimal? RMANum { get; set; }
        //public decimal? RMALine { get; set; }
        //public string? ProjectID { get; set; }
        //public decimal? ContractNum { get; set; }
        //public string? ContractCode { get; set; }
        //public string? BasePartNum { get; set; }
        //public bool Warranty { get; set; }
        //public string? WarrantyCode { get; set; }
        //public decimal? MaterialDuration { get; set; }
        //public decimal? LaborDuration { get; set; }
        //public decimal? MiscDuration { get; set; }
        //public string? MaterialMod { get; set; }
        //public string? LaborMod { get; set; }
        //public string? WarrantyComment { get; set; }
        //public bool Onsite { get; set; }
        //public bool MatCovered { get; set; }
        //public bool LabCovered { get; set; }
        //public bool MiscCovered { get; set; }
        //public string? SalesUM { get; set; }
        //public decimal? SellingFactor { get; set; }
        //public decimal? SellingQuantity { get; set; }
        //public string? SalesCatID { get; set; }
        //public bool ShipLineComplete { get; set; }
        //public decimal? CumeQty { get; set; }
        //public DateTime? CumeDate { get; set; }
        //public string? MktgCampaignID { get; set; }
        //public decimal? MktgEvntSeq { get; set; }
        //public bool LockQty { get; set; }
        //public bool Linked { get; set; }
        //public decimal? ICPONum { get; set; }
        //public decimal? ICPOLine { get; set; }
        //public string? ExtCompany { get; set; }
        //public DateTime? LastConfigDate { get; set; }
        //public decimal? LastConfigTime { get; set; }
        //public string? LastConfigUserID { get; set; }
        //public decimal? ConfigUnitPrice { get; set; }
        //public decimal? ConfigBaseUnitPrice { get; set; }
        //public string? PriceListCode { get; set; }
        //public string? BreakListCode { get; set; }
        //public decimal? PricingQty { get; set; }
        //public bool LockPrice { get; set; }
        //public decimal? ListPrice { get; set; }
        //public decimal? DocListPrice { get; set; }
        //public decimal? OrdBasedPrice { get; set; }
        //public decimal? DocOrdBasedPrice { get; set; }
        //public string? PriceGroupCode { get; set; }
        //public bool OverridePriceList { get; set; }
        //public string? BaseRevisionNum { get; set; }
        //public decimal? PricingValue { get; set; }
        //public decimal? DisplaySeq { get; set; }
        //public decimal? KitParentLine { get; set; }
        //public bool KitAllowUpdate { get; set; }
        //public bool KitShipComplete { get; set; }
        //public bool KitBackFlush { get; set; }
        //public bool KitPrintCompsPS { get; set; }
        //public bool KitPrintCompsInv { get; set; }
        //public string? KitPricing { get; set; }
        //public decimal? KitQtyPer { get; set; }
        //public string? SellingFactorDirection { get; set; }
        //public decimal? RepRate1 { get; set; }
        //public decimal? RepRate2 { get; set; }
        //public decimal? RepRate3 { get; set; }
        //public decimal? RepRate4 { get; set; }
        //public decimal? RepRate5 { get; set; }
        //public decimal? RepSplit1 { get; set; }
        //public decimal? RepSplit2 { get; set; }
        //public decimal? RepSplit3 { get; set; }
        //public decimal? RepSplit4 { get; set; }
        //public decimal? RepSplit5 { get; set; }
        //public decimal? DemandContractLine { get; set; }
        //public bool CreateNewJob { get; set; }
        //public DateTime? DoNotShipBeforeDate { get; set; }
        //public bool GetDtls { get; set; }
        //public DateTime? DoNotShipAfterDate { get; set; }
        //public bool SchedJob { get; set; }
        //public bool RelJob { get; set; }
        //public bool EnableCreateNewJob { get; set; }
        //public bool EnableGetDtls { get; set; }
        //public bool EnableSchedJob { get; set; }
        //public bool EnableRelJob { get; set; }
        //public string? CounterSaleWarehouse { get; set; }
        //public string? CounterSaleBinNum { get; set; }
        //public string? CounterSaleLotNum { get; set; }
        //public string? CounterSaleDimCode { get; set; }
        //public bool DemandDtlRejected { get; set; }
        //public string? KitFlag { get; set; }
        //public bool KitsLoaded { get; set; }
        //public decimal? DemandContractNum { get; set; }
        //public decimal? DemandHeadSeq { get; set; }
        //public decimal? DemandDtlSeq { get; set; }
        //public string? ChangedBy { get; set; }
        //public DateTime? ChangeDate { get; set; }
        //public decimal? ChangeTime { get; set; }
        //public bool ReverseCharge { get; set; }
        //public decimal? TotalReleases { get; set; }
        //public decimal? Rpt1UnitPrice { get; set; }
        //public decimal? Rpt2UnitPrice { get; set; }
        //public decimal? Rpt3UnitPrice { get; set; }
        //public decimal? Rpt1Discount { get; set; }
        //public decimal? Rpt2Discount { get; set; }
        //public decimal? Rpt3Discount { get; set; }
        //public decimal? Rpt1AdvanceBillBal { get; set; }
        //public decimal? Rpt2AdvanceBillBal { get; set; }
        //public decimal? Rpt3AdvanceBillBal { get; set; }
        //public decimal? Rpt1ListPrice { get; set; }
        //public decimal? Rpt2ListPrice { get; set; }
        //public decimal? Rpt3ListPrice { get; set; }
        //public decimal? Rpt1OrdBasedPrice { get; set; }
        //public decimal? Rpt2OrdBasedPrice { get; set; }
        //public decimal? Rpt3OrdBasedPrice { get; set; }
        //public decimal? ExtPriceDtl { get; set; }
        //public decimal? DocExtPriceDtl { get; set; }
        //public decimal? Rpt1ExtPriceDtl { get; set; }
        //public decimal? Rpt2ExtPriceDtl { get; set; }
        //public decimal? Rpt3ExtPriceDtl { get; set; }
        //public string? LineStatus { get; set; }
        //public decimal? InUnitPrice { get; set; }
        //public decimal? DocInUnitPrice { get; set; }
        //public decimal? InDiscount { get; set; }
        //public decimal? DocInDiscount { get; set; }
        //public decimal? InListPrice { get; set; }
        //public decimal? DocInListPrice { get; set; }
        //public decimal? InOrdBasedPrice { get; set; }
        //public decimal? DocInOrdBasedPrice { get; set; }
        //public decimal? Rpt1InUnitPrice { get; set; }
        //public decimal? Rpt2InUnitPrice { get; set; }
        //public decimal? Rpt3InUnitPrice { get; set; }
        //public decimal? Rpt1InDiscount { get; set; }
        //public decimal? Rpt2InDiscount { get; set; }
        //public decimal? Rpt3InDiscount { get; set; }
        //public decimal? Rpt1InListPrice { get; set; }
        //public decimal? Rpt2InListPrice { get; set; }
        //public decimal? Rpt3InListPrice { get; set; }
        //public decimal? Rpt1InOrdBasedPrice { get; set; }
        //public decimal? Rpt2InOrdBasedPrice { get; set; }
        //public decimal? Rpt3InOrdBasedPrice { get; set; }
        //public decimal? InExtPriceDtl { get; set; }
        //public decimal? DocInExtPriceDtl { get; set; }
        //public decimal? Rpt1InExtPriceDtl { get; set; }
        //public decimal? Rpt2InExtPriceDtl { get; set; }
        //public decimal? Rpt3InExtPriceDtl { get; set; }
        //public decimal? OldOurOpenQty { get; set; }
        //public decimal? OldSellingOpenQty { get; set; }
        //public decimal? OldOpenValue { get; set; }
        //public string? OldProdCode { get; set; }
        //public decimal? PrevSellQty { get; set; }
        //public string? PrevPartNum { get; set; }
        //public string? PrevXPartNum { get; set; }
        //public decimal? KitCompOrigSeq { get; set; }
        //public string? KitCompOrigPart { get; set; }
        //public bool SmartStringProcessed { get; set; }
        //public string? SmartString { get; set; }
        //public decimal? RenewalNbr { get; set; }
        //public string? DiscBreakListCode { get; set; }
        //public decimal? DiscListPrice { get; set; }
        //public bool LockDisc { get; set; }
        //public bool OverrideDiscPriceList { get; set; }
        //public decimal? GroupSeq { get; set; }
        //public string? ECCOrderNum { get; set; }
        //public decimal? ECCOrderLine { get; set; }
        //public bool DupOnJobCrt { get; set; }
        //public decimal? UndersPct { get; set; }
        //public decimal? Overs { get; set; }
        //public decimal? Unders { get; set; }
        //public decimal? OversUnitPrice { get; set; }
        //public string? PlanUserID { get; set; }
        //public string? PlanGUID { get; set; }
        //public string? MOMsourceType { get; set; }
        //public string? MOMsourceEst { get; set; }
        //public string? DefaultOversPricing { get; set; }
        //public string? ECCPlant { get; set; }
        //public string? ECCQuoteNum { get; set; }
        //public decimal? ECCQuoteLine { get; set; }
        //public decimal? SysRevID { get; set; }
        //public string? SysRowID { get; set; }
        //public string? MfgJobType { get; set; }
        //public string? ProFormaInvComment { get; set; }
        //public bool CreateJob { get; set; }
        //public string? ContractID { get; set; }
        //public bool LinkToContract { get; set; }
        //public decimal? DocInAdvanceBillBal { get; set; }
        //public decimal? InAdvanceBillBal { get; set; }
        //public decimal? Rpt1InAdvanceBillBal { get; set; }
        //public decimal? Rpt2InAdvanceBillBal { get; set; }
        //public decimal? Rpt3InAdvanceBillBal { get; set; }
        //public bool PCLinkRemoved { get; set; }
        //public string? CommodityCode { get; set; }
        //public decimal? MSRP { get; set; }
        //public decimal? DocMSRP { get; set; }
        //public decimal? Rpt1MSRP { get; set; }
        //public decimal? Rpt2MSRP { get; set; }
        //public decimal? Rpt3MSRP { get; set; }
        //public decimal? EndCustomerPrice { get; set; }
        //public decimal? DocEndCustomerPrice { get; set; }
        //public decimal? Rpt1EndCustomerPrice { get; set; }
        //public decimal? Rpt2EndCustomerPrice { get; set; }
        //public decimal? Rpt3EndCustomerPrice { get; set; }
        //public decimal? PromotionalPrice { get; set; }
        //public decimal? DocPromotionalPrice { get; set; }
        //public decimal? Rpt1PromotionalPrice { get; set; }
        //public decimal? Rpt2PromotionalPrice { get; set; }
        //public decimal? Rpt3PromotionalPrice { get; set; }
        //public string? OrderLineStatusCode { get; set; }
        //public decimal? AttributeSetID { get; set; }
        //public decimal? KBConfigProdID { get; set; }
        //public decimal? KBOriginalConfigProdID { get; set; }
        //public decimal? AvailableQuantity { get; set; }
        //public string? AvailPriceLists { get; set; }
        //public string? AvailUMFromQuote { get; set; }
        //public string? BaseCurrencyID { get; set; }
        //public string? BaseCurrSymbol { get; set; }
        //public decimal? CalcUnitPrice { get; set; }
        //public string? ConfigType { get; set; }
        //public string? Configured { get; set; }
        //public bool CounterSale { get; set; }
        //public string? CreditLimitMessage { get; set; }
        //public string? CreditLimitSource { get; set; }
        //public string? CurrencyCode { get; set; }
        //public string? CurrencyID { get; set; }
        //public bool CurrencySwitch { get; set; }
        //public string? CurrSymbol { get; set; }
        //public decimal? DemandQuantity { get; set; }
        //public string? DimCode { get; set; }
        //public decimal? DimConvFactor { get; set; }
        //public decimal? DocDspDiscount { get; set; }
        //public decimal? DocDspUnitPrice { get; set; }
        //public decimal? DocExtPrice { get; set; }
        //public decimal? DocInMiscCharges { get; set; }
        //public decimal? DocLessDiscount { get; set; }
        //public decimal? DocMiscCharges { get; set; }
        //public decimal? DocTaxAmt { get; set; }
        //public decimal? DocTotalPrice { get; set; }
        //public decimal? DspDiscount { get; set; }
        //public string? DspJobType { get; set; }
        //public decimal? DspUnitPrice { get; set; }
        //public string? DUM { get; set; }
        //public string? ECCConfigSysRowId { get; set; }
        //public decimal? ECCDiscount { get; set; }
        //public bool ECCPreventRepricing { get; set; }
        //public bool EnableDynAttrButton { get; set; }
        //public bool EnableKitUnitPrice { get; set; }
        //public bool EnableRenewalNbr { get; set; }
        //public bool EnableSellingQty { get; set; }
        //public string? EntryProcess { get; set; }
        //public decimal? ExtPrice { get; set; }
        //public bool FromQuoteLineFlag { get; set; }
        //public decimal? FSAInstallationCost { get; set; }
        //public decimal? FSAInstallationOrderLine { get; set; }
        //public decimal? FSAInstallationOrderNum { get; set; }
        //public bool FSAInstallationRequired { get; set; }
        //public string? FSAInstallationType { get; set; }
        //public string? FSAInstallationTypeDescription { get; set; }
        //public bool HasComplement { get; set; }
        //public bool HasDowngrade { get; set; }
        //public bool HasSubstitute { get; set; }
        //public bool HasUpgrade { get; set; }
        //public decimal? InMiscCharges { get; set; }
        //public bool InPrice { get; set; }
        //public string? IntExternalKey { get; set; }
        //public string? InvtyUOM { get; set; }
        //public string? JobTypeDesc { get; set; }
        //public bool JobWasCreated { get; set; }
        //public bool KitChangeParms { get; set; }
        //public bool KitDisable { get; set; }
        //public string? KitFlagDescription { get; set; }
        //public string? KitOrderQtyUOM { get; set; }
        //public bool KitStandard { get; set; }
        //public decimal? LessDiscount { get; set; }
        //public string? LotNum { get; set; }
        //public decimal? MiscCharges { get; set; }
        //public bool MultipleReleases { get; set; }
        //public decimal? OnHandQuantity { get; set; }
        //public bool PartExists { get; set; }
        //public bool PartTrackDimension { get; set; }
        //public bool PartTrackLots { get; set; }
        //public string? POLineRef { get; set; }
        //public string? PriceListCodeDesc { get; set; }
        //public bool ProcessCounterSale { get; set; }
        //public bool ProcessQuickEntry { get; set; }
        //public decimal? QuoteQtyNum { get; set; }
        //public bool RelWasRecInvoiced { get; set; }
        //public string? RespMessage { get; set; }
        //public decimal? Rpt1DspDiscount { get; set; }
        //public decimal? Rpt1DspUnitPrice { get; set; }
        //public decimal? Rpt1ExtPrice { get; set; }
        //public decimal? Rpt1InMiscCharges { get; set; }
        //public decimal? Rpt1LessDiscount { get; set; }
        //public decimal? Rpt1MiscCharges { get; set; }
        //public decimal? Rpt1TaxAmt { get; set; }
        //public decimal? Rpt1TotalPrice { get; set; }
        //public decimal? Rpt2DspDiscount { get; set; }
        //public decimal? Rpt2DspUnitPrice { get; set; }
        //public decimal? Rpt2ExtPrice { get; set; }
        //public decimal? Rpt2InMiscCharges { get; set; }
        //public decimal? Rpt2LessDiscount { get; set; }
        //public decimal? Rpt2MiscCharges { get; set; }
        //public decimal? Rpt2TaxAmt { get; set; }
        //public decimal? Rpt2TotalPrice { get; set; }
        //public decimal? Rpt3DspDiscount { get; set; }
        //public decimal? Rpt3DspUnitPrice { get; set; }
        //public decimal? Rpt3ExtPrice { get; set; }
        //public decimal? Rpt3InMiscCharges { get; set; }
        //public decimal? Rpt3LessDiscount { get; set; }
        //public decimal? Rpt3MiscCharges { get; set; }
        //public decimal? Rpt3TaxAmt { get; set; }
        //public decimal? Rpt3TotalPrice { get; set; }
        //public string? SalesRepName1 { get; set; }
        //public string? SalesRepName2 { get; set; }
        //public string? SalesRepName3 { get; set; }
        //public string? SalesRepName4 { get; set; }
        //public string? SalesRepName5 { get; set; }
        //public decimal? TaxAmt { get; set; }
        //public decimal? ThisOrderInvtyQty { get; set; }
        //public decimal? TotalPrice { get; set; }
        //public decimal? TotalShipped { get; set; }
        //public string? WarehouseCode { get; set; }
        //public string? WarehouseDesc { get; set; }
        //public string? BinNum { get; set; }
        //public bool AttributeMismatch { get; set; }
        //public string? JobManagerString { get; set; }
        //public decimal? CalcOrdBasedPrice { get; set; }
        //public bool SalesOrderLinked { get; set; }
        //public decimal? InventoryAttributeSetID { get; set; }
        //public decimal? BitFlag { get; set; }
        //public string? CommodityCodeDescription { get; set; }
        //public string? ContractCodeContractDescription { get; set; }
        //public bool CustNumSendToFSA { get; set; }
        //public string? CustNumBTName { get; set; }
        //public string? CustNumCustID { get; set; }
        //public string? CustNumName { get; set; }
        //public string? DiscBreakListCodeListDescription { get; set; }
        //public DateTime? DiscBreakListCodeEndDate { get; set; }
        //public DateTime? DiscBreakListCodeStartDate { get; set; }
        //public string? MktgCampaignIDCampDescription { get; set; }
        //public string? MktgEvntEvntDescription { get; set; }
        //public decimal? OrderNumBTCustNum { get; set; }
        //public string? OrderNumCurrencyCode { get; set; }
        //public string? OrderNumCardMemberName { get; set; }
        //public bool PartNumSendToFSA { get; set; }
        //public string? PartNumAttrClassID { get; set; }
        //public string? PartNumSalesUM { get; set; }
        //public string? PartNumPricePerCode { get; set; }
        //public bool PartNumTrackSerialNum { get; set; }
        //public string? PartNumPartDescription { get; set; }
        //public string? PartNumIUM { get; set; }
        //public bool PartNumTrackLots { get; set; }
        //public decimal? PartNumSellingFactor { get; set; }
        //public bool PartNumTrackDimension { get; set; }
        //public decimal? PartNumDefaultAttributeSetID { get; set; }
        //public bool PartNumFSAEquipment { get; set; }
        //public bool PartNumTrackInventoryAttributes { get; set; }
        //public string? PriceBreakListDescription { get; set; }
        //public DateTime? PriceBreakStartDate { get; set; }
        //public DateTime? PriceBreakEndDate { get; set; }
        //public string? ProdCodeDescription { get; set; }
        //public string? ProjectIDDescription { get; set; }
        //public string? QuoteNumCurrencyCode { get; set; }
        //public string? SalesCatIDDescription { get; set; }
        //public string? TaxCatIDDescription { get; set; }
        //public string? WarrantyCodeWarrDescription { get; set; }
        //public string? RowMod { get; set; }
        //public string? UD_SysRevID { get; set; }
        //public decimal? PbsId_c { get; set; }
        //public DateTime? PbsEarlyShipDate_c { get; set; }
        //public decimal? PbsEarlyShipDays_c { get; set; }
        //public decimal? NetPricePerUOM_c { get; set; }
        //public decimal? LineTotalWOdisc_c { get; set; }
        //public decimal? PartCost_c { get; set; }
        //public decimal? GPPercent_c { get; set; }
        //public decimal? GPAmount_c { get; set; }
        //public decimal? DocNetPricePerUOM_c { get; set; }
        //public decimal? DocLineTotalWOdisc_c { get; set; }
        //public decimal? DocPartCost_c { get; set; }
        //public decimal? DocGPAmount_c { get; set; }
        //public string? PbsPurchOrderComments_c { get; set; }
        //public string? MealTime_c { get; set; }
        //public List<OrderMsc>? OrderMscs { get; set; }
        //public List<OrderRel>? OrderRels { get; set; }
        //public List<OrderDtlAttch>? OrderDtlAttches { get; set; }
    }

    public class OHOrderMsc
    {
        public string? Company { get; set; }
        public decimal? OrderNum { get; set; }
        public decimal? OrderLine { get; set; }
        public decimal? SeqNum { get; set; }
        public string? MiscCode { get; set; }
        public string? Description { get; set; }
        public decimal? MiscAmt { get; set; }
        public decimal? DocMiscAmt { get; set; }
        public string? FreqCode { get; set; }
        public string? Quoting { get; set; }
        public bool Linked { get; set; }
        public decimal? ICPONum { get; set; }
        public decimal? ICPOLine { get; set; }
        public decimal? ICPOSeqNum { get; set; }
        public string? ExtCompany { get; set; }
        public string? ChangedBy { get; set; }
        public DateTime? ChangeDate { get; set; }
        public decimal? ChangeTime { get; set; }
        public decimal? Rpt1MiscAmt { get; set; }
        public decimal? Rpt2MiscAmt { get; set; }
        public decimal? Rpt3MiscAmt { get; set; }
        public decimal? InMiscAmt { get; set; }
        public decimal? DocInMiscAmt { get; set; }
        public decimal? Rpt1InMiscAmt { get; set; }
        public decimal? Rpt2InMiscAmt { get; set; }
        public decimal? Rpt3InMiscAmt { get; set; }
        public decimal? Percentage { get; set; }
        public string? Type { get; set; }
        public bool ChangeTrackApproved { get; set; }
        public decimal? ChangeTrackAmount { get; set; }
        public string? ChangeTrackMemoDesc { get; set; }
        public string? ChangeTrackMemoText { get; set; }
        public string? ChangeTrackStatus { get; set; }
        public decimal? SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public string? BaseCurrSymbol { get; set; }
        public string? CurrencyCode { get; set; }
        public bool CurrencySwitch { get; set; }
        public string? CurrSymbol { get; set; }
        public decimal? DocDspMiscAmt { get; set; }
        public decimal? DspMiscAmt { get; set; }
        public string? EntryProcess { get; set; }
        public decimal? Rpt1DspMiscAmt { get; set; }
        public decimal? Rpt2DspMiscAmt { get; set; }
        public decimal? Rpt3DspMiscAmt { get; set; }
        public string? RespMessage { get; set; }
        public decimal? BitFlag { get; set; }
        public string? MiscCodeDescription { get; set; }
        public string? OrderNumCardMemberName { get; set; }
        public string? OrderNumCurrencyCode { get; set; }
        public string? RowMod { get; set; }
    }


    public class OrderDtlAttch
    {
        public string? Company { get; set; }
        public decimal? OrderNum { get; set; }
        public decimal? OrderLine { get; set; }
        public decimal? DrawingSeq { get; set; }
        public decimal? XFileRefNum { get; set; }
        public decimal? SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public string? ForeignSysRowID { get; set; }
        public string? DrawDesc { get; set; }
        public string? FileName { get; set; }
        public string? PDMDocID { get; set; }
        public string? DocTypeID { get; set; }
        public string? RowMod { get; set; }
    }

    public class OrderHedAttch
    {
        public string? Company { get; set; }
        public decimal? OrderNum { get; set; }
        public decimal? DrawingSeq { get; set; }
        public decimal? XFileRefNum { get; set; }
        public decimal? SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public string? ForeignSysRowID { get; set; }
        public string? DrawDesc { get; set; }
        public string? FileName { get; set; }
        public string? PDMDocID { get; set; }
        public string? DocTypeID { get; set; }
        public string? RowMod { get; set; }
    }

    public class OrderHedUP
    {
        public string? Company { get; set; }
        public decimal? OrderNum { get; set; }
        public decimal? UPSQVSeq { get; set; }
        public string? EmailAddress { get; set; }
        public bool ShipmentNotify { get; set; }
        public bool FailureNotify { get; set; }
        public bool DeliveryNotify { get; set; }
        public decimal? SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public bool EnableQuantumView { get; set; }
        public string? EntryProcess { get; set; }
        public decimal? BitFlag { get; set; }
        public string? RowMod { get; set; }
    }

    public class OrderMsc
    {
        public string? Company { get; set; }
        public decimal? OrderNum { get; set; }
        public decimal? OrderLine { get; set; }
        public decimal? SeqNum { get; set; }
        public string? MiscCode { get; set; }
        public string? Description { get; set; }
        public decimal? MiscAmt { get; set; }
        public decimal? DocMiscAmt { get; set; }
        public string? FreqCode { get; set; }
        public string? Quoting { get; set; }
        public bool Linked { get; set; }
        public decimal? ICPONum { get; set; }
        public decimal? ICPOLine { get; set; }
        public decimal? ICPOSeqNum { get; set; }
        public string? ExtCompany { get; set; }
        public string? ChangedBy { get; set; }
        public DateTime? ChangeDate { get; set; }
        public decimal? ChangeTime { get; set; }
        public decimal? Rpt1MiscAmt { get; set; }
        public decimal? Rpt2MiscAmt { get; set; }
        public decimal? Rpt3MiscAmt { get; set; }
        public decimal? InMiscAmt { get; set; }
        public decimal? DocInMiscAmt { get; set; }
        public decimal? Rpt1InMiscAmt { get; set; }
        public decimal? Rpt2InMiscAmt { get; set; }
        public decimal? Rpt3InMiscAmt { get; set; }
        public decimal? Percentage { get; set; }
        public string? Type { get; set; }
        public bool ChangeTrackApproved { get; set; }
        public decimal? ChangeTrackAmount { get; set; }
        public string? ChangeTrackMemoDesc { get; set; }
        public string? ChangeTrackMemoText { get; set; }
        public string? ChangeTrackStatus { get; set; }
        public decimal? SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public string? BaseCurrSymbol { get; set; }
        public string? CurrencyCode { get; set; }
        public bool CurrencySwitch { get; set; }
        public string? CurrSymbol { get; set; }
        public decimal? DocDspMiscAmt { get; set; }
        public decimal? DspMiscAmt { get; set; }
        public string? EntryProcess { get; set; }
        public bool OpenLine { get; set; }
        public decimal? Rpt1DspMiscAmt { get; set; }
        public decimal? Rpt2DspMiscAmt { get; set; }
        public decimal? Rpt3DspMiscAmt { get; set; }
        public string? RespMessage { get; set; }
        public decimal? BitFlag { get; set; }
        public string? MiscCodeDescription { get; set; }
        public string? OrderLineLineDesc { get; set; }
        public string? OrderNumCurrencyCode { get; set; }
        public string? OrderNumCardMemberName { get; set; }
        public string? RowMod { get; set; }
    }

    public class OrderRel
    {
        public string? Company { get; set; }
        public decimal? OrderNum { get; set; }
        public decimal? OrderLine { get; set; }
        public decimal? OrderRelNum { get; set; }
        public string? LineType { get; set; }
        public DateTime? ReqDate { get; set; }
        public decimal? OurReqQty { get; set; }
        public string? ShipToNum { get; set; }
        public string? ShipViaCode { get; set; }
        public bool OpenRelease { get; set; }
        public bool FirmRelease { get; set; }
        public bool Make { get; set; }
        public decimal? OurJobQty { get; set; }
        public decimal? OurJobShippedQty { get; set; }
        public bool VoidRelease { get; set; }
        public decimal? OurStockQty { get; set; }
        public string? WarehouseCode { get; set; }
        public decimal? OurStockShippedQty { get; set; }
        public string? PartNum { get; set; }
        public string? RevisionNum { get; set; }
        public string? TaxExempt { get; set; }
        public decimal? ShpConNum { get; set; }
        public DateTime? NeedByDate { get; set; }
        public string? Reference { get; set; }
        public string? Plant { get; set; }
        public decimal? SellingReqQty { get; set; }
        public decimal? SellingJobQty { get; set; }
        public decimal? SellingJobShippedQty { get; set; }
        public decimal? SellingStockQty { get; set; }
        public decimal? SellingStockShippedQty { get; set; }
        public bool SelectForPicking { get; set; }
        public string? StagingWarehouseCode { get; set; }
        public string? StagingBinNum { get; set; }
        public string? PickError { get; set; }
        public decimal? CumeQty { get; set; }
        public DateTime? CumeDate { get; set; }
        public bool Linked { get; set; }
        public decimal? ICPONum { get; set; }
        public decimal? ICPOLine { get; set; }
        public decimal? ICPORelNum { get; set; }
        public string? ExtCompany { get; set; }
        public string? ScheduleNumber { get; set; }
        public string? MarkForNum { get; set; }
        public string? DropShipName { get; set; }
        public string? RAN { get; set; }
        public string? DemandReference { get; set; }
        public bool DemandSchedRejected { get; set; }
        public DateTime? DatePickTicketPrinted { get; set; }
        public bool ResDelivery { get; set; }
        public bool SatDelivery { get; set; }
        public bool SatPickup { get; set; }
        public bool VerbalConf { get; set; }
        public bool Hazmat { get; set; }
        public bool DocOnly { get; set; }
        public string? RefNotes { get; set; }
        public bool ApplyChrg { get; set; }
        public decimal? ChrgAmount { get; set; }
        public bool COD { get; set; }
        public bool CODFreight { get; set; }
        public bool CODCheck { get; set; }
        public decimal? CODAmount { get; set; }
        public string? GroundType { get; set; }
        public bool NotifyFlag { get; set; }
        public string? NotifyEMail { get; set; }
        public bool DeclaredIns { get; set; }
        public decimal? DeclaredAmt { get; set; }
        public bool ServSatDelivery { get; set; }
        public bool ServSatPickup { get; set; }
        public bool ServSignature { get; set; }
        public bool ServAlert { get; set; }
        public bool ServPOD { get; set; }
        public bool ServAOD { get; set; }
        public bool ServHomeDel { get; set; }
        public string? DeliveryType { get; set; }
        public DateTime? ServDeliveryDate { get; set; }
        public string? ServPhone { get; set; }
        public string? ServInstruct { get; set; }
        public bool ServRelease { get; set; }
        public string? ServAuthNum { get; set; }
        public string? ServRef1 { get; set; }
        public string? ServRef2 { get; set; }
        public string? ServRef3 { get; set; }
        public string? ServRef4 { get; set; }
        public string? ServRef5 { get; set; }
        public bool OverrideCarrier { get; set; }
        public bool OverrideService { get; set; }
        public string? DockingStation { get; set; }
        public string? Location { get; set; }
        public string? TransportID { get; set; }
        public decimal? ShipbyTime { get; set; }
        public string? ChangedBy { get; set; }
        public DateTime? ChangeDate { get; set; }
        public decimal? ChangeTime { get; set; }
        public bool TaxConnectCalc { get; set; }
        public bool GetDfltTaxIds { get; set; }
        public string? TaxRegionCode { get; set; }
        public bool UseOTS { get; set; }
        public string? OTSName { get; set; }
        public string? OTSAddress1 { get; set; }
        public string? OTSAddress2 { get; set; }
        public string? OTSAddress3 { get; set; }
        public string? OTSCity { get; set; }
        public string? OTSState { get; set; }
        public string? OTSZIP { get; set; }
        public string? OTSResaleID { get; set; }
        public string? OTSContact { get; set; }
        public string? OTSFaxNum { get; set; }
        public string? OTSPhoneNum { get; set; }
        public decimal? OTSCountryNum { get; set; }
        public string? SubShipTo { get; set; }
        public string? ShipRouting { get; set; }
        public bool BuyToOrder { get; set; }
        public decimal? VendorNum { get; set; }
        public string? PurPoint { get; set; }
        public bool DropShip { get; set; }
        public decimal? PONum { get; set; }
        public decimal? POLine { get; set; }
        public decimal? PORelNum { get; set; }
        public bool OpenOrder { get; set; }
        public string? OTSSaveAs { get; set; }
        public string? OTSSaveCustID { get; set; }
        public bool OTSCustSaved { get; set; }
        public decimal? ShipToCustNum { get; set; }
        public string? IUM { get; set; }
        public string? SalesUM { get; set; }
        public string? RelStatus { get; set; }
        public string? ComplianceMsg { get; set; }
        public decimal? PrevSellQty { get; set; }
        public string? PrevPartNum { get; set; }
        public string? PrevXPartNum { get; set; }
        public DateTime? PrevNeedByDate { get; set; }
        public DateTime? PrevReqDate { get; set; }
        public string? PrevShipToNum { get; set; }
        public decimal? MFCustNum { get; set; }
        public bool UseOTMF { get; set; }
        public string? OTMFName { get; set; }
        public string? OTMFAddress1 { get; set; }
        public string? OTMFAddress2 { get; set; }
        public string? OTMFAddress3 { get; set; }
        public string? OTMFCity { get; set; }
        public string? OTMFState { get; set; }
        public string? OTMFZIP { get; set; }
        public string? OTMFContact { get; set; }
        public string? OTMFFaxNum { get; set; }
        public string? OTMFPhoneNum { get; set; }
        public decimal? OTMFCountryNum { get; set; }
        public string? ECCPlant { get; set; }
        public string? WIOrderLine { get; set; }
        public string? WIOrder { get; set; }
        public string? WebSKU { get; set; }
        public bool ShipOvers { get; set; }
        public decimal? WIItemPrice { get; set; }
        public decimal? WIItemShipCost { get; set; }
        public decimal? SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public string? EntityUseCode { get; set; }
        public string? PhaseID { get; set; }
        public string? OTSShipToNum { get; set; }
        public bool WasRecInvoiced { get; set; }
        public string? ContractID { get; set; }
        public bool LinkToContract { get; set; }
        public bool ReadyToFulfill { get; set; }
        public string? OTSEMailAddress { get; set; }
        public decimal? AttributeSetID { get; set; }
        public decimal? NumberOfPieces { get; set; }
        public string? NumberOfPiecesUOM { get; set; }
        public decimal? PlanningNumberOfPieces { get; set; }
        public string? PartAllocQueueAction { get; set; }
        public decimal? OTSTaxValidationStatus { get; set; }
        public DateTime? OTSTaxValidationDate { get; set; }
        public decimal? AvailableQuantity { get; set; }
        public bool BuyOverride { get; set; }
        public string? CreditLimitMessage { get; set; }
        public string? CreditLimitSource { get; set; }
        public string? CurrencyCode { get; set; }
        public bool CustAllowOTS { get; set; }
        public bool CustomerAllowShipTo3 { get; set; }
        public string? CustomerCustID { get; set; }
        public string? CustomerName { get; set; }
        public bool DisablePlantWhse { get; set; }
        public decimal? DocSelfAssessTax { get; set; }
        public decimal? DocTotalTax { get; set; }
        public decimal? DocWithholdTax { get; set; }
        public bool DropShipOverride { get; set; }
        public string? DspInvMeth { get; set; }
        public string? DspRevMethod { get; set; }
        public bool EnableBuyToOrder { get; set; }
        public bool EnableMake { get; set; }
        public string? EntryProcess { get; set; }
        public bool ExistPOSugg { get; set; }
        public bool HdrOTS { get; set; }
        public string? IntExternalKey { get; set; }
        public string? InvtyUOM { get; set; }
        public bool KitDisable { get; set; }
        public bool LinkToPONum { get; set; }
        public bool MakeOverride { get; set; }
        public string? MarkForAddrFormatted { get; set; }
        public string? MarkForAddrList { get; set; }
        public string? MFCustID { get; set; }
        public bool NoRelTaxRgnChange { get; set; }
        public bool NotCompliant { get; set; }
        public decimal? OnHandQuantity { get; set; }
        public bool OTSSaved { get; set; }
        public string? OTSTaxRegionCode { get; set; }
        public bool PartExists { get; set; }
        public bool PhaseWasRecInvoiced { get; set; }
        public string? ProjectID { get; set; }
        public string? ReleaseStatus { get; set; }
        public bool RemoveManAdTax { get; set; }
        public decimal? Rpt1SelfAssessTax { get; set; }
        public decimal? Rpt1TotalTax { get; set; }
        public decimal? Rpt1WithholdTax { get; set; }
        public decimal? Rpt2SelfAssessTax { get; set; }
        public decimal? Rpt2TotalTax { get; set; }
        public decimal? Rpt2WithholdTax { get; set; }
        public decimal? Rpt3SelfAssessTax { get; set; }
        public decimal? Rpt3TotalTax { get; set; }
        public decimal? Rpt3WithholdTax { get; set; }
        public bool SalesOrderLinked { get; set; }
        public decimal? SelfAssessTax { get; set; }
        public decimal? SellingFactor { get; set; }
        public string? SellingFactorDirection { get; set; }
        public string? ShipToAddressFormatted { get; set; }
        public string? ShipToAddressList { get; set; }
        public string? ShipToContactEMailAddress { get; set; }
        public string? ShipToContactName { get; set; }
        public bool ShipToSelected { get; set; }
        public bool SNEnable { get; set; }
        public decimal? ThisRelInvtyQty { get; set; }
        public decimal? TotalJobStockShipped { get; set; }
        public decimal? TotalTax { get; set; }
        public bool UpdateMarkForRecords { get; set; }
        public bool VoidOrder { get; set; }
        public decimal? WithholdTax { get; set; }
        public bool AllowTaxCodeUpd { get; set; }
        public bool EnableDynAttrButton { get; set; }
        public bool AttributeMismatch { get; set; }
        public decimal? AllocatedQuantity { get; set; }
        public string? ErrorStatusDisplay { get; set; }
        public bool InPartAllocQueue { get; set; }
        public bool ShowAllocationQueueActions { get; set; }
        public decimal? BitFlag { get; set; }
        public string? DynAttrValueSetShortDescription { get; set; }
        public string? DynAttrValueSetDescription { get; set; }
        public bool MFCustNumInactive { get; set; }
        public string? OrderLineLineDesc { get; set; }
        public string? OrderNumCurrencyCode { get; set; }
        public string? OrderNumCardMemberName { get; set; }
        public string? OTMFCountryDescription { get; set; }
        public string? OTSCntryISOCode { get; set; }
        public bool OTSCntryEUMember { get; set; }
        public string? OTSCntryDescription { get; set; }
        public bool PartNumTrackInventoryAttributes { get; set; }
        public string? PartNumAttrClassID { get; set; }
        public string? PartNumPricePerCode { get; set; }
        public bool PartNumTrackDimension { get; set; }
        public string? PartNumIUM { get; set; }
        public bool PartNumTrackSerialNum { get; set; }
        public string? PartNumPartDescription { get; set; }
        public bool PartNumTrackLots { get; set; }
        public decimal? PartNumSellingFactor { get; set; }
        public string? PartNumSalesUM { get; set; }
        public string? PlantName { get; set; }
        public string? PurPointAddress3 { get; set; }
        public string? PurPointZip { get; set; }
        public string? PurPointName { get; set; }
        public string? PurPointCountry { get; set; }
        public string? PurPointAddress1 { get; set; }
        public string? PurPointState { get; set; }
        public string? PurPointCity { get; set; }
        public string? PurPointAddress2 { get; set; }
        public decimal? PurPointPrimPCon { get; set; }
        public string? ShipViaCodeWebDesc { get; set; }
        public string? ShipViaCodeDescription { get; set; }
        public string? TaxRegionCodeDescription { get; set; }
        public string? TPShipToName { get; set; }
        public string? TPShipToBTName { get; set; }
        public string? TPShipToCustID { get; set; }
        public string? VendorNumState { get; set; }
        public string? VendorNumZIP { get; set; }
        public string? VendorNumName { get; set; }
        public string? VendorNumAddress2 { get; set; }
        public string? VendorNumCountry { get; set; }
        public string? VendorNumCurrencyCode { get; set; }
        public string? VendorNumCity { get; set; }
        public string? VendorNumAddress3 { get; set; }
        public string? VendorNumVendorID { get; set; }
        public string? VendorNumDefaultFOB { get; set; }
        public string? VendorNumTermsCode { get; set; }
        public string? VendorNumAddress1 { get; set; }
        public string? WarehouseCodeDescription { get; set; }
        public string? RowMod { get; set; }
        public string? UD_SysRevID { get; set; }
        public bool PbsDefaultTaxRemoved_c { get; set; }
        public bool PbsTaxCalculated_c { get; set; }
        public bool PbsLinkedToTransferOrder_c { get; set; }
        public string? PbsPickedBy_c { get; set; }
        public DateTime? PbsPickedDate_c { get; set; }
        public bool PbsPickedRel_c { get; set; }
        public bool PbsPickedPrinted_c { get; set; }
        public string? PBSTargetPCID_c { get; set; }
        public DateTime? pbsEarlyShipDate_c { get; set; }
        public decimal? pbsRFQNum_c { get; set; }
        public string? pbsSupplierComments_c { get; set; }
        public decimal? PbsEarlyShipDays_c { get; set; }
        public string? PbsSupplierContact_c { get; set; }
        public bool PbsPCIDShipped_c { get; set; }
        public string? PbsLoadID_c { get; set; }
        public string? PbsSupplierPart_c { get; set; }
        public decimal? PbsPurchaseCost_c { get; set; }
        public decimal? PbsPurchaseQty_c { get; set; }
        public string? PbsPurchaseUOM_c { get; set; }
        public string? ShortChar01 { get; set; }
        public decimal? PbsAllocateJrnyNum_c { get; set; }
        public DateTime? PlannedShipDate_c { get; set; }
        public DateTime? PlannedDeliveryDate_c { get; set; }
        public string? pbsSPNotes_c { get; set; }
        public decimal? PbsJourneyNum_c { get; set; }
        public bool PbsBuyToOrder_c { get; set; }
        public bool PbsDropShip_c { get; set; }
        public List<OrderRelTaxis>? OrderRelTaxes { get; set; }
    }

    public class OrderRelTaxis
    {
        public string? Company { get; set; }
        public string? TaxCode { get; set; }
        public decimal? ReportableAmt { get; set; }
        public decimal? DocReportableAmt { get; set; }
        public decimal? TaxableAmt { get; set; }
        public decimal? DocTaxableAmt { get; set; }
        public decimal? Percent { get; set; }
        public decimal? TaxAmt { get; set; }
        public decimal? DocTaxAmt { get; set; }
        public bool Manual { get; set; }
        public string? ChangedBy { get; set; }
        public DateTime? ChangeDate { get; set; }
        public decimal? ChangeTime { get; set; }
        public bool ReverseCharge { get; set; }
        public decimal? OrderNum { get; set; }
        public decimal? OrderLine { get; set; }
        public decimal? OrderRelNum { get; set; }
        public decimal? Discount { get; set; }
        public decimal? DocDiscount { get; set; }
        public decimal? Rpt1Discount { get; set; }
        public decimal? Rpt2Discount { get; set; }
        public decimal? Rpt3Discount { get; set; }
        public decimal? Rpt1ReportableAmt { get; set; }
        public decimal? Rpt2ReportableAmt { get; set; }
        public decimal? Rpt3ReportableAmt { get; set; }
        public decimal? Rpt1TaxableAmt { get; set; }
        public decimal? Rpt2TaxableAmt { get; set; }
        public decimal? Rpt3TaxableAmt { get; set; }
        public decimal? Rpt1TaxAmt { get; set; }
        public decimal? Rpt2TaxAmt { get; set; }
        public decimal? Rpt3TaxAmt { get; set; }
        public string? RateCode { get; set; }
        public decimal? CollectionType { get; set; }
        public decimal? Timing { get; set; }
        public decimal? ExemptType { get; set; }
        public decimal? ExemptPercent { get; set; }
        public string? ResolutionNum { get; set; }
        public DateTime? ResolutionDate { get; set; }
        public DateTime? TaxRateDate { get; set; }
        public decimal? DefTaxableAmt { get; set; }
        public decimal? DocDefTaxableAmt { get; set; }
        public decimal? Rpt1DefTaxableAmt { get; set; }
        public decimal? Rpt2DefTaxableAmt { get; set; }
        public decimal? Rpt3DefTaxableAmt { get; set; }
        public decimal? DefTaxAmt { get; set; }
        public decimal? DocDefTaxAmt { get; set; }
        public decimal? Rpt1DefTaxAmt { get; set; }
        public decimal? Rpt2DefTaxAmt { get; set; }
        public decimal? Rpt3DefTaxAmt { get; set; }
        public bool ManAdd { get; set; }
        public decimal? DedTaxAmt { get; set; }
        public decimal? DocDedTaxAmt { get; set; }
        public decimal? Rpt1DedTaxAmt { get; set; }
        public decimal? Rpt2DedTaxAmt { get; set; }
        public decimal? Rpt3DedTaxAmt { get; set; }
        public decimal? ECAcquisitionSeq { get; set; }
        public decimal? FixedAmount { get; set; }
        public decimal? DocFixedAmount { get; set; }
        public decimal? Rpt1FixedAmount { get; set; }
        public decimal? Rpt2FixedAmount { get; set; }
        public decimal? Rpt3FixedAmount { get; set; }
        public string? TextCode { get; set; }
        public decimal? SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public string? SalesTaxDescDescription { get; set; }
        public string? DocDisplaySymbol { get; set; }
        public bool CurrencySwitch { get; set; }
        public string? CurrencyCode { get; set; }
        public string? CollectionTypeDescription { get; set; }
        public string? DisplaySymbol { get; set; }
        public bool NoChangeManual { get; set; }
        public string? EntryProcess { get; set; }
        public decimal? BitFlag { get; set; }
        public string? RateCodeDescDescription { get; set; }
        public string? RowMod { get; set; }
    }

    public class OrderRepComm
    {
        public string? Company { get; set; }
        public decimal? OrderNum { get; set; }
        public string? SalesRepCode { get; set; }
        public string? Name { get; set; }
        public decimal? CommLines { get; set; }
        public decimal? CommSaleAmt { get; set; }
        public decimal? CommAmt { get; set; }
        public string? Seq { get; set; }
        public string? SysRowID { get; set; }
        public string? RowMod { get; set; }
    }

    public class OrderSched
    {
        public string? Company { get; set; }
        public decimal? OrderNum { get; set; }
        public decimal? PaySeq { get; set; }
        public decimal? PayDays { get; set; }
        public decimal? PayPercent { get; set; }
        public decimal? PayAmount { get; set; }
        public decimal? SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public decimal? DocPayAmount { get; set; }
        public decimal? Rpt1PayAmount { get; set; }
        public decimal? Rpt2PayAmount { get; set; }
        public decimal? Rpt3PayAmount { get; set; }
        public bool CurrencySwitch { get; set; }
        public string? CurrencyCode { get; set; }
        public bool IsLastRow { get; set; }
        public decimal? BitFlag { get; set; }
        public string? RowMod { get; set; }
    }

}
