// ReSharper disable InconsistentNaming
namespace KairosWebAPI.Models.Dto
{
    public class UpdateVendorDto
    {
        public bool? Inactive { get; set; }
        public string? Company { get; set; }
        public string? VendorID { get; set; }
        public string? Name { get; set; }
        public int VendorNum { get; set; }
        public string? Address1 { get; set; }
        public string? Address2 { get; set; }
        public string? Address3 { get; set; }
        public string? City { get; set; }
        public string? State { get; set; }
        public string? ZIP { get; set; }
        public string? Country { get; set; }
        public string? TaxPayerID { get; set; }
        public string? PurPoint { get; set; }
        public string? TermsCode { get; set; }
        public string? GroupCode { get; set; }
        public bool? Print1099 { get; set; }
        public bool? OneCheck { get; set; }
        public bool? PrintLabels { get; set; }
        public string? FaxNum { get; set; }
        public string? PhoneNum { get; set; }
        public string? Comment { get; set; }
        public bool? payhold { get; set; }
        public int? primpcon { get; set; }
        public string? accountref { get; set; }
        public string? defaultfob { get; set; }
        public bool? rcvinspectionreq { get; set; }
        public string? currencycode { get; set; }
        public string? taxregioncode { get; set; }
        public int? countrynum { get; set; }
        public string? langnameid { get; set; }
        public string? bordercrossing { get; set; }
        public string? formatstr { get; set; }
        public bool? elecpayment { get; set; }
        public string? primarybankid { get; set; }
        public bool? approved { get; set; }
        public bool? icvend { get; set; }
        public string? emailaddress { get; set; }
        public bool? webvendor { get; set; }
        public string? VendURL { get; set; }
        public int? EarlyBuffer { get; set; }
        public int? LateBuffer { get; set; }
        public string? OnTimeRating { get; set; }
        public string? QualityRating { get; set; }
        public string? PriceRating { get; set; }
        public string? ServiceRating { get; set; }
        public string? ExternalId { get; set; }
        public int? VendPILimit { get; set; }
        public bool? GlobalVendor { get; set; }
        public bool? ICTrader { get; set; }
        public string? TaxAuthorityCode { get; set; }
        public bool? GlobalLock { get; set; }
        public decimal? MinOrderValue { get; set; }
        public string? CalendarID { get; set; }
        public string? EDICode { get; set; }
        public bool? ConsolidatedPurchasing { get; set; }
        public bool? LocalPurchasing { get; set; }
        public bool? ResDelivery { get; set; }
        public bool? SatDelivery { get; set; }
        public bool? SatPickup { get; set; }
        public bool? Hazmat { get; set; }
        public bool? DocOnly { get; set; }
        public string? RefNotes { get; set; }
        public bool? ApplyChrg { get; set; }
        public int? ChrgAmount { get; set; }
        public bool? COD { get; set; }
        public bool? CODFreight { get; set; }
        public bool? CODCheck { get; set; }
        public double? CODAmount { get; set; }
        public string? GroundType { get; set; }
        public bool? NotifyFlag { get; set; }
        public string? NotifyEMail { get; set; }
        public bool? DeclaredIns { get; set; }
        public int? DeclaredAmt { get; set; }
        public bool? ServSignature { get; set; }
        public bool? ServAlert { get; set; }
        public bool? ServHomeDel { get; set; }
        public string? DeliveryType { get; set; }
        public DateTime? ServDeliveryDate { get; set; }
        public string? ServPhone { get; set; }
        public string? ServInstruct { get; set; }
        public bool? ServRelease { get; set; }
        public string? ServAuthNum { get; set; }
        public string? ServRef1 { get; set; }
        public string? ServRef2 { get; set; }
        public string? ServRef3 { get; set; }
        public string? ServRef4 { get; set; }
        public string? ServRef5 { get; set; }
        public bool? CPay { get; set; }
        public bool? IndividualPackIDs { get; set; }
        public bool? IntrntlShip { get; set; }
        public bool? CertOfOrigin { get; set; }
        public bool? CommercialInvoice { get; set; }
        public bool? ShipExprtDeclartn { get; set; }
        public bool? LetterOfInstr { get; set; }
        public string? FFID { get; set; }
        public string? FFCompName { get; set; }
        public string? FFContact { get; set; }
        public string? FFAddress1 { get; set; }
        public string? FFAddress2 { get; set; }
        public string? FFAddress3 { get; set; }
        public string? FFCity { get; set; }
        public string? FFState { get; set; }
        public string? FFZip { get; set; }
        public string? FFCountry { get; set; }
        public bool? NonStdPkg { get; set; }
        public int? DeliveryConf { get; set; }
        public bool? AddlHdlgFlag { get; set; }
        public bool? UPSQuantumView { get; set; }
        public string? UPSQVShipFromName { get; set; }
        public string? UPSQVMemo { get; set; }
        public string? FFPhoneNum { get; set; }
        public int? FFCountryNum { get; set; }
        public string? RevChargeMethod { get; set; }
        public bool? ManagedCust { get; set; }
        public string? ManagedCustID { get; set; }
        public int? ManagedCustNum { get; set; }
        public int? PMUID { get; set; }
        public bool? HasBank { get; set; }
        public string? PmtAcctRef { get; set; }
        public string? LegalName { get; set; }
        public string? TaxRegReason { get; set; }
        public string? OrgRegCode { get; set; }
        public bool? AdvTaxInv { get; set; }
        public bool? AllowAsAltRemitTo { get; set; }
        public double? SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public string? THBranchID { get; set; }
        public string? ParamCode { get; set; }
        public string? AGAFIPResponsibilityCode { get; set; }
        public string? AGGrossIncomeTaxID { get; set; }
        public string? AGIDDocumentTypeCode { get; set; }
        public string? AGProvinceCode { get; set; }
        public bool? AGUseGoodDefaultMark { get; set; }
        public string? AGApartment { get; set; }
        public string? AGExtraStreetNumber { get; set; }
        public string? AGFloor { get; set; }
        public string? AGLocationCode { get; set; }
        public string? AGNeighborhood { get; set; }
        public string? AGStreet { get; set; }
        public string? AGStreetNumber { get; set; }
        public string? COOneTimeID { get; set; }
        public bool? NoBankingReference { get; set; }
        public bool? PEGoodsContributor { get; set; }
        public bool? PEWithholdAgent { get; set; }
        public bool? PECollectionAgent { get; set; }
        public bool? PENotFound { get; set; }
        public bool? PENoAddress { get; set; }
        public string? PEIdentityDocType { get; set; }
        public bool? COIsOneTimeVend { get; set; }
        public string? PEDocumentID { get; set; }
        public int? MaxLateDaysPORel { get; set; }
        public string? Code1099ID { get; set; }
        public string? TIN { get; set; }
        public string? TINType { get; set; }
        public bool? SecondTINNotice { get; set; }
        public string? NameControl { get; set; }
        public string? ShipViaCode { get; set; }
        public bool? NonUS { get; set; }
        public string? FormTypeID { get; set; }
        public string? INSupplierType { get; set; }
        public string? INCSTNumber { get; set; }
        public string? INPANNumber { get; set; }
        public string? DEOrgType { get; set; }
        public bool? PaymentReporting { get; set; }
        public bool? ExternalPurchasing { get; set; }
        public string? MXRetentionCode { get; set; }
        public string? Reporting1099Name { get; set; }
        public string? Reporting1099Name2 { get; set; }
        public bool? FATCA { get; set; }
        public string? AccountNum { get; set; }
        public string? TWGUIRegNum { get; set; }
        public string? MXTARCode { get; set; }
        public string? PEAddressID { get; set; }
        public string? PERetentionRegime { get; set; }
        public string? TaxEntityType { get; set; }
        public int? INGSTComplianceRate { get; set; }
        public string? INTaxRegistrationID { get; set; }
        public int? TINValidationStatus { get; set; }
        public bool? ImporterOfRecord { get; set; }
        public bool? PLAutomaticAPInvoiceNum { get; set; }
        public string? SEC { get; set; }
        public string? MXDIOTTranType { get; set; }
        public string? US1099KMerchCatCode { get; set; }
        public string? MXTaxpayerType { get; set; }
        public string? MXLegalRepRFC { get; set; }
        public string? MXLegalRepCURP { get; set; }
        public string? MXLegalRepName { get; set; }
        public string? MXLegalRepTaxpayerType { get; set; }
        public string? US1099State { get; set; }
        public int? TaxValidationStatus { get; set; }
        public DateTime? TaxValidationDate { get; set; }
        public string? HMRCTaxValidationLog { get; set; }
        public string? ExternalSchemeID { get; set; }
        public string? MXMunicipio { get; set; }
        public bool? EInvoice { get; set; }
        public string? BusinessCatList { get; set; }
        public string? COASegReferences { get; set; }
        public string? CountryDescription { get; set; }
        public string? CurrDesc { get; set; }
        public string? DocumentMaskID { get; set; }
        public bool? EnableGlobalLock { get; set; }
        public bool? EnableGlobalVendor { get; set; }
        public bool? EnableMultiCompany { get; set; }
        public bool? EnableRevCharge { get; set; }
        public string? FOBDescription { get; set; }
        public bool? GlbFlag { get; set; }
        public string? GlbLink { get; set; }
        public bool? Integrationflag { get; set; }
        public string? NettingCustID { get; set; }
        public int? NettingCustNum { get; set; }
        public string? RevChargeMethodDesc { get; set; }
        public string? SalesTaxID { get; set; }
        public string? SearchIDs { get; set; }
        public string? ServiceTaxID { get; set; }
        public string? ShipViaDescription { get; set; }
        public string? VendAttrString { get; set; }
        public string? LangNameIDDescription { get; set; }
        public int? BitFlag { get; set; }
        public string? AGAFIPResponsibilityDescription { get; set; }
        public string? AGIDDocTypeDescription { get; set; }
        public string? AGLocationDescription { get; set; }
        public string? AGProvinceCodeDescription { get; set; }
        public string? CalendarIDDescription { get; set; }
        public string? Code1099Description { get; set; }
        public bool? CountryNumEUMember { get; set; }
        public string? CountryNumISOCode { get; set; }
        public string? CountryNumDescription { get; set; }
        public string? CurrencyCodeCurrSymbol { get; set; }
        public string? CurrencyCodeDocumentDesc { get; set; }
        public string? CurrencyCodeCurrencyID { get; set; }
        public string? CurrencyCodeCurrName { get; set; }
        public string? CurrencyCodeCurrDesc { get; set; }
        public string? DeliveryTypeDescription { get; set; }
        public string? FormTypeDescription { get; set; }
        public string? GroupCodeGroupDesc { get; set; }
        public int? PayMethodType { get; set; }
        public string? PayMethodName { get; set; }
        public bool? PayMethodSummarizePerCustomer { get; set; }
        public string? PurPointAddress3 { get; set; }
        public string? PurPointAddress1 { get; set; }
        public int? PurPointPrimPCon { get; set; }
        public string? PurPointName { get; set; }
        public string? PurPointZip { get; set; }
        public string? PurPointCountry { get; set; }
        public string? PurPointCity { get; set; }
        public string? PurPointState { get; set; }
        public string? PurPointAddress2 { get; set; }
        public string? TaxAuthCdTaxAuthorityDescription { get; set; }
        public string? TaxRegionCodeDescription { get; set; }
        public string? TermsCodeDescription { get; set; }
        //public string? RowMod { get; set; }
        //public string? UD_SysRevID { get; set; }
        public bool? KWebPO_c { get; set; }
        //public List<EntityGLC>? EntityGLCs { get; set; }
        //public List<TaxExempt>? TaxExempts { get; set; }
        //public List<PEVendWhldHist>? PEVendWhldHists { get; set; }
        //public List<VendRestriction>? VendRestrictions { get; set; }
        //public List<VendBank>? VendBanks { get; set; }
        //public List<VendCntMain>? VendCntMains { get; set; }
        //public List<VenMFBill>? VenMFBills { get; set; }
        //public List<VendorPP>? VendorPPs { get; set; }
        //public List<VenUPSEmail>? VenUPSEmails { get; set; }
        //public List<VendorAttch>? VendorAttches { get; set; }
    }

}
