// ReSharper disable InconsistentNaming
namespace KairosWebAPI.Models.Dto
{

    public class Vendor
    {
        public bool? Inactive { get; set; }
        public string? Company { get; set; }
        public string? VendorID { get; set; }
        public string? Name { get; set; }
        public int VendorNum { get; set; }
        public string? Address1 { get; set; }
        public string? Address2 { get; set; }
        public string? Address3 { get; set; }
        public string? City { get; set; }
        public string? State { get; set; }
        public string? ZIP { get; set; }
        public string? Country { get; set; }
        public string? TaxPayerID { get; set; }
        public string? PurPoint { get; set; }
        public string? TermsCode { get; set; }
        public string? GroupCode { get; set; }
        public bool? Print1099 { get; set; }
        public bool? OneCheck { get; set; }
        public bool? PrintLabels { get; set; }
        public string? FaxNum { get; set; }
        public string? PhoneNum { get; set; }
        public string? Comment { get; set; }
        public bool PayHold { get; set; }
        public int PrimPCon { get; set; }
        public string? AccountRef { get; set; }
        public string? DefaultFOB { get; set; }
        public bool RcvInspectionReq { get; set; }
        public string? CurrencyCode { get; set; }
        public string? TaxRegionCode { get; set; }
        public int CountryNum { get; set; }
        public string? LangNameID { get; set; }
        public string? BorderCrossing { get; set; }
        public string? FormatStr { get; set; }
        public bool ElecPayment { get; set; }
        public string? PrimaryBankID { get; set; }
        public bool Approved { get; set; }
        public bool ICVend { get; set; }
        public string? EMailAddress { get; set; }
        public bool WebVendor { get; set; }
        public string? VendURL { get; set; }
        public int EarlyBuffer { get; set; }
        public int LateBuffer { get; set; }
        public string? OnTimeRating { get; set; }
        public string? QualityRating { get; set; }
        public string? PriceRating { get; set; }
        public string? ServiceRating { get; set; }
        public string? ExternalId { get; set; }
        public int VendPILimit { get; set; }
        public bool GlobalVendor { get; set; }
        public bool ICTrader { get; set; }
        public string? TaxAuthorityCode { get; set; }
        public bool GlobalLock { get; set; }
        public decimal? MinOrderValue { get; set; }
        public string? CalendarID { get; set; }
        public string? EDICode { get; set; }
        public bool ConsolidatedPurchasing { get; set; }
        public bool LocalPurchasing { get; set; }
        public bool ResDelivery { get; set; }
        public bool SatDelivery { get; set; }
        public bool SatPickup { get; set; }
        public bool Hazmat { get; set; }
        public bool DocOnly { get; set; }
        public string? RefNotes { get; set; }
        public bool ApplyChrg { get; set; }
        public int ChrgAmount { get; set; }
        public bool COD { get; set; }
        public bool CODFreight { get; set; }
        public bool CODCheck { get; set; }
        public decimal CODAmount { get; set; }
        public string? GroundType { get; set; }
        public bool NotifyFlag { get; set; }
        public string? NotifyEMail { get; set; }
        public bool DeclaredIns { get; set; }
        public int DeclaredAmt { get; set; }
        public bool ServSignature { get; set; }
        public bool ServAlert { get; set; }
        public bool ServHomeDel { get; set; }
        public string? DeliveryType { get; set; }
        public DateTime? ServDeliveryDate { get; set; }
        public string? ServPhone { get; set; }
        public string? ServInstruct { get; set; }
        public bool ServRelease { get; set; }
        public string? ServAuthNum { get; set; }
        public string? ServRef1 { get; set; }
        public string? ServRef2 { get; set; }
        public string? ServRef3 { get; set; }
        public string? ServRef4 { get; set; }
        public string? ServRef5 { get; set; }
        public bool CPay { get; set; }
        public bool IndividualPackIDs { get; set; }
        public bool IntrntlShip { get; set; }
        public bool CertOfOrigin { get; set; }
        public bool CommercialInvoice { get; set; }
        public bool ShipExprtDeclartn { get; set; }
        public bool LetterOfInstr { get; set; }
        public string? FFID { get; set; }
        public string? FFCompName { get; set; }
        public string? FFContact { get; set; }
        public string? FFAddress1 { get; set; }
        public string? FFAddress2 { get; set; }
        public string? FFAddress3 { get; set; }
        public string? FFCity { get; set; }
        public string? FFState { get; set; }
        public string? FFZip { get; set; }
        public string? FFCountry { get; set; }
        public bool NonStdPkg { get; set; }
        public int DeliveryConf { get; set; }
        public bool AddlHdlgFlag { get; set; }
        public bool UPSQuantumView { get; set; }
        public string? UPSQVShipFromName { get; set; }
        public string? UPSQVMemo { get; set; }
        public string? FFPhoneNum { get; set; }
        public int FFCountryNum { get; set; }
        public string? RevChargeMethod { get; set; }
        public bool ManagedCust { get; set; }
        public string? ManagedCustID { get; set; }
        public int ManagedCustNum { get; set; }
        public int PMUID { get; set; }
        public bool HasBank { get; set; }
        public string? PmtAcctRef { get; set; }
        public string? LegalName { get; set; }
        public string? TaxRegReason { get; set; }
        public string? OrgRegCode { get; set; }
        public bool AdvTaxInv { get; set; }
        public bool AllowAsAltRemitTo { get; set; }
        public decimal SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public string? THBranchID { get; set; }
        public string? ParamCode { get; set; }
        public string? AGAFIPResponsibilityCode { get; set; }
        public string? AGGrossIncomeTaxID { get; set; }
        public string? AGIDDocumentTypeCode { get; set; }
        public string? AGProvinceCode { get; set; }
        public bool AGUseGoodDefaultMark { get; set; }
        public string? AGApartment { get; set; }
        public string? AGExtraStreetNumber { get; set; }
        public string? AGFloor { get; set; }
        public string? AGLocationCode { get; set; }
        public string? AGNeighborhood { get; set; }
        public string? AGStreet { get; set; }
        public string? AGStreetNumber { get; set; }
        public string? COOneTimeID { get; set; }
        public bool NoBankingReference { get; set; }
        public bool PEGoodsContributor { get; set; }
        public bool PEWithholdAgent { get; set; }
        public bool PECollectionAgent { get; set; }
        public bool PENotFound { get; set; }
        public bool PENoAddress { get; set; }
        public string? PEIdentityDocType { get; set; }
        public bool COIsOneTimeVend { get; set; }
        public string? PEDocumentID { get; set; }
        public int MaxLateDaysPORel { get; set; }
        public string? Code1099ID { get; set; }
        public string? TIN { get; set; }
        public string? TINType { get; set; }
        public bool SecondTINNotice { get; set; }
        public string? NameControl { get; set; }
        public string? ShipViaCode { get; set; }
        public bool NonUS { get; set; }
        public string? FormTypeID { get; set; }
        public string? INSupplierType { get; set; }
        public string? INCSTNumber { get; set; }
        public string? INPANNumber { get; set; }
        public string? DEOrgType { get; set; }
        public bool PaymentReporting { get; set; }
        public bool ExternalPurchasing { get; set; }
        public string? MXRetentionCode { get; set; }
        public string? Reporting1099Name { get; set; }
        public string? Reporting1099Name2 { get; set; }
        public bool FATCA { get; set; }
        public string? AccountNum { get; set; }
        public string? TWGUIRegNum { get; set; }
        public string? MXTARCode { get; set; }
        public string? PEAddressID { get; set; }
        public string? PERetentionRegime { get; set; }
        public string? TaxEntityType { get; set; }
        public int INGSTComplianceRate { get; set; }
        public string? INTaxRegistrationID { get; set; }
        public int TINValidationStatus { get; set; }
        public bool ImporterOfRecord { get; set; }
        public bool PLAutomaticAPInvoiceNum { get; set; }
        public string? SEC { get; set; }
        public string? MXDIOTTranType { get; set; }
        public string? US1099KMerchCatCode { get; set; }
        public string? MXTaxpayerType { get; set; }
        public string? MXLegalRepRFC { get; set; }
        public string? MXLegalRepCURP { get; set; }
        public string? MXLegalRepName { get; set; }
        public string? MXLegalRepTaxpayerType { get; set; }
        public string? US1099State { get; set; }
        public int TaxValidationStatus { get; set; }
        public DateTime? TaxValidationDate { get; set; }
        public string? HMRCTaxValidationLog { get; set; }
        public string? ExternalSchemeID { get; set; }
        public string? MXMunicipio { get; set; }
        public bool EInvoice { get; set; }
        public string? BusinessCatList { get; set; }
        public string? COASegReferences { get; set; }
        public string? CountryDescription { get; set; }
        public string? CurrDesc { get; set; }
        public string? DocumentMaskID { get; set; }
        public bool EnableGlobalLock { get; set; }
        public bool EnableGlobalVendor { get; set; }
        public bool EnableMultiCompany { get; set; }
        public bool EnableRevCharge { get; set; }
        public string? FOBDescription { get; set; }
        public bool GlbFlag { get; set; }
        public string? GlbLink { get; set; }
        public bool Integrationflag { get; set; }
        public string? NettingCustID { get; set; }
        public int NettingCustNum { get; set; }
        public string? RevChargeMethodDesc { get; set; }
        public string? SalesTaxID { get; set; }
        public string? SearchIDs { get; set; }
        public string? ServiceTaxID { get; set; }
        public string? ShipViaDescription { get; set; }
        public string? VendAttrString { get; set; }
        public string? LangNameIDDescription { get; set; }
        public int BitFlag { get; set; }
        public string? AGAFIPResponsibilityDescription { get; set; }
        public string? AGIDDocTypeDescription { get; set; }
        public string? AGLocationDescription { get; set; }
        public string? AGProvinceCodeDescription { get; set; }
        public string? CalendarIDDescription { get; set; }
        public string? Code1099Description { get; set; }
        public bool CountryNumEUMember { get; set; }
        public string? CountryNumISOCode { get; set; }
        public string? CountryNumDescription { get; set; }
        public string? CurrencyCodeCurrSymbol { get; set; }
        public string? CurrencyCodeDocumentDesc { get; set; }
        public string? CurrencyCodeCurrencyID { get; set; }
        public string? CurrencyCodeCurrName { get; set; }
        public string? CurrencyCodeCurrDesc { get; set; }
        public string? DeliveryTypeDescription { get; set; }
        public string? FormTypeDescription { get; set; }
        public string? GroupCodeGroupDesc { get; set; }
        public int PayMethodType { get; set; }
        public string? PayMethodName { get; set; }
        public bool PayMethodSummarizePerCustomer { get; set; }
        public string? PurPointAddress3 { get; set; }
        public string? PurPointAddress1 { get; set; }
        public int PurPointPrimPCon { get; set; }
        public string? PurPointName { get; set; }
        public string? PurPointZip { get; set; }
        public string? PurPointCountry { get; set; }
        public string? PurPointCity { get; set; }
        public string? PurPointState { get; set; }
        public string? PurPointAddress2 { get; set; }
        public string? TaxAuthCdTaxAuthorityDescription { get; set; }
        public string? TaxRegionCodeDescription { get; set; }
        public string? TermsCodeDescription { get; set; }
        public string? RowMod { get; set; }
        public string? UD_SysRevID { get; set; }
        public bool KWebPO_c { get; set; }
    }

    public class EntityGLC
    {
        public string? Company { get; set; }
        public string? RelatedToFile { get; set; }
        public string? Key1 { get; set; }
        public string? Key2 { get; set; }
        public string? Key3 { get; set; }
        public string? Key4 { get; set; }
        public string? Key5 { get; set; }
        public string? Key6 { get; set; }
        public string? GLControlType { get; set; }
        public string? GLControlCode { get; set; }
        public string? BusinessEntity { get; set; }
        public string? ExtCompanyID { get; set; }
        public bool IsExternalCompany { get; set; }
        public bool GlobalEntityGLC { get; set; }
        public bool GlobalLock { get; set; }
        public int SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public string? BankAcctID { get; set; }
        public string? BankFeeID { get; set; }
        public string? CallCode { get; set; }
        public string? ChargeCode { get; set; }
        public string? ClassCode { get; set; }
        public string? ClassID { get; set; }
        public string? ContractCode { get; set; }
        public string? CurrencyCode { get; set; }
        public int CustNum { get; set; }
        public string? DeductionID { get; set; }
        public string? EmpID { get; set; }
        public string? ExpenseCode { get; set; }
        public string? ExtSystemID { get; set; }
        public string? FromPlant { get; set; }
        public string? GroupCode { get; set; }
        public string? GroupID { get; set; }
        public int HeadNum { get; set; }
        public string? InvoiceNum { get; set; }
        public string? JCDept { get; set; }
        public string? MiscCode { get; set; }
        public string? PartNum { get; set; }
        public string? PayTypeID { get; set; }
        public string? PerConName { get; set; }
        public string? PIStatus { get; set; }
        public string? Plant { get; set; }
        public string? ProdCode { get; set; }
        public string? ProjectID { get; set; }
        public string? PurchCode { get; set; }
        public string? RateCode { get; set; }
        public string? ReasonCode { get; set; }
        public string? ReasonType { get; set; }
        public string? SalesCatID { get; set; }
        public int Shift { get; set; }
        public string? TaxCode { get; set; }
        public string? TaxTblID { get; set; }
        public string? ToPlant { get; set; }
        public string? TransferMethod { get; set; }
        public string? TypeID { get; set; }
        public int VendorNum { get; set; }
        public string? WarehouseCode { get; set; }
        public string? ExpenseTypeCode { get; set; }
        public bool IsFiltered { get; set; }
        public string? OprTypeCode { get; set; }
        public string? CashDeskID { get; set; }
        public string? TIN { get; set; }
        public string? ReclassCodeID { get; set; }
        public int BitFlag { get; set; }
        public string? GLCntrlDescription { get; set; }
        public string? GLCntrlTypeDescription { get; set; }
        public string? RowMod { get; set; }
    }

    public class PEVendWhldHist
    {
        public string? Company { get; set; }
        public int VendorNum { get; set; }
        public int RecordSeq { get; set; }
        public DateTime CreateDate { get; set; }
        public string? UserID { get; set; }
        public string? IdentityDocType { get; set; }
        public bool GoodContributor { get; set; }
        public bool WithholdingAgent { get; set; }
        public bool CollectionAgent { get; set; }
        public bool NotFound { get; set; }
        public bool NoAddress { get; set; }
        public int SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public int BitFlag { get; set; }
        public string? RowMod { get; set; }
    }
    public class TaxExempt
    {
        public string? Company { get; set; }
        public string? RelatedToFile { get; set; }
        public string? Key1 { get; set; }
        public string? Key2 { get; set; }
        public string? TaxCode { get; set; }
        public string? RateCode { get; set; }
        public DateTime EffectiveFrom { get; set; }
        public DateTime EffectiveTo { get; set; }
        public int ExemptType { get; set; }
        public int ExemptPercent { get; set; }
        public string? TextCode { get; set; }
        public string? ResolutionNum { get; set; }
        public DateTime ResolutionDate { get; set; }
        public int SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public int CustNum { get; set; }
        public string? PartNum { get; set; }
        public int VendorNum { get; set; }
        public int BitFlag { get; set; }
        public string? SalesTaxDescription { get; set; }
        public string? SalesTRCDescription { get; set; }
        public string? TaxTextDescription { get; set; }
        public string? RowMod { get; set; }
    }

    public class VendBank
    {
        public string? Company { get; set; }
        public int VendorNum { get; set; }
        public string? BankID { get; set; }
        public string? BankName { get; set; }
        public string? Address1 { get; set; }
        public string? Address2 { get; set; }
        public string? Address3 { get; set; }
        public string? City { get; set; }
        public string? State { get; set; }
        public string? PostalCode { get; set; }
        public int CountryNum { get; set; }
        public string? BankAcctNumber { get; set; }
        public string? NameOnAccount { get; set; }
        public string? SwiftNum { get; set; }
        public int PMUID { get; set; }
        public string? BankBranchCode { get; set; }
        public string? IBANCode { get; set; }
        public string? SECreditTransNum { get; set; }
        public string? LegalName { get; set; }
        public string? CorrespAccount { get; set; }
        public string? LocalBIC { get; set; }
        public string? BankPersonCode { get; set; }
        public string? VendAccountType { get; set; }
        public string? CardCode { get; set; }
        public string? BankGiroAcctNbr { get; set; }
        public string? BankRefCode { get; set; }
        public bool AllowAsAltRemitToBank { get; set; }
        public string? DFIIdentification { get; set; }
        public int SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public string? CHDTAID { get; set; }
        public string? CHISRPartyID { get; set; }
        public string? FeeOwnership { get; set; }
        public string? POBankAcctNum { get; set; }
        public string? BankCustNum { get; set; }
        public int BankCustNumberStartPos { get; set; }
        public int BankCustNumberLen { get; set; }
        public string? BAddress1 { get; set; }
        public string? BAddress2 { get; set; }
        public string? BAddress3 { get; set; }
        public string? BankCharges { get; set; }
        public string? BankCnstSymbol { get; set; }
        public string? BankSpecSymbol { get; set; }
        public string? BankType { get; set; }
        public string? BCity { get; set; }
        public int BCountryNum { get; set; }
        public string? BPostalCode { get; set; }
        public string? BState { get; set; }
        public string? NOChequeCode { get; set; }
        public string? NOFeeCostCode { get; set; }
        public string? ReceiverName { get; set; }
        public string? ReceivingBankName { get; set; }
        public string? ReceivingBankNum { get; set; }
        public string? ReceivingBranchName { get; set; }
        public string? ReceivingBranchNum { get; set; }
        public string? SEBankFeeCostOwner { get; set; }
        public bool PEDetractionsNBA { get; set; }
        public string? MXSATCode { get; set; }
        public string? MXSATNameShort { get; set; }
        public string? MXSATNameFull { get; set; }
        public string? DKCreditorNum { get; set; }
        public string? PayID { get; set; }
        public string? ClearSystemIDCode { get; set; }
        public string? MemberID { get; set; }
        public int BCountry { get; set; }
        public string? CHScrPOBankAcctNum { get; set; }
        public bool PrimaryBank { get; set; }
        public string? CHScrISRPartyID { get; set; }
        public int BitFlag { get; set; }
        public string? BankBranchCodeDescDescription { get; set; }
        public string? BankBranchCodeDescBankBranchCode { get; set; }
        public string? BCountryNumDescription { get; set; }
        public string? CountryNumDescription { get; set; }
        public int PayMethodType { get; set; }
        public bool PayMethodSummarizePerCustomer { get; set; }
        public string? PayMethodName { get; set; }
        public string? VendorNumCity { get; set; }
        public string? VendorNumState { get; set; }
        public string? VendorNumVendorID { get; set; }
        public string? VendorNumAddress1 { get; set; }
        public string? VendorNumName { get; set; }
        public string? VendorNumDefaultFOB { get; set; }
        public string? VendorNumCurrencyCode { get; set; }
        public string? VendorNumCountry { get; set; }
        public string? VendorNumAddress2 { get; set; }
        public string? VendorNumAddress3 { get; set; }
        public string? VendorNumZIP { get; set; }
        public string? VendorNumTermsCode { get; set; }
        public string? RowMod { get; set; }
        public List<VendBankAttch>? VendBankAttches { get; set; }
    }

    public class VendBankAttch
    {
        public string? Company { get; set; }
        public int VendorNum { get; set; }
        public string? BankID { get; set; }
        public int DrawingSeq { get; set; }
        public int XFileRefNum { get; set; }
        public int SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public string? ForeignSysRowID { get; set; }
        public string? DrawDesc { get; set; }
        public string? FileName { get; set; }
        public string? PDMDocID { get; set; }
        public string? DocTypeID { get; set; }
        public string? RowMod { get; set; }
    }

    public class VendCnt
    {
        public string? Company { get; set; }
        public int VendorNum { get; set; }
        public string? PurPoint { get; set; }
        public int ConNum { get; set; }
        public string? Name { get; set; }
        public string? Func { get; set; }
        public string? FaxNum { get; set; }
        public string? PhoneNum { get; set; }
        public string? EmailAddress { get; set; }
        public string? WebPassword { get; set; }
        public bool WebUser { get; set; }
        public string? RoleCode { get; set; }
        public string? CellPhoneNum { get; set; }
        public string? PagerNum { get; set; }
        public string? HomeNum { get; set; }
        public string? AltNum { get; set; }
        public string? ContactTitle { get; set; }
        public string? ReportsTo { get; set; }
        public string? Comment { get; set; }
        public bool NoContact { get; set; }
        public DateTime CreateDate { get; set; }
        public string? CreateDcdUserID { get; set; }
        public DateTime ChangeDate { get; set; }
        public string? ChangeDcdUserID { get; set; }
        public bool Inactive { get; set; }
        public string? FirstName { get; set; }
        public string? MiddleName { get; set; }
        public string? LastName { get; set; }
        public string? Prefix { get; set; }
        public string? Suffix { get; set; }
        public string? Initials { get; set; }
        public string? ExternalId { get; set; }
        public bool GlobalLock { get; set; }
        public int PerConID { get; set; }
        public bool SyncEmailToPerCon { get; set; }
        public bool SyncLinksToPerCon { get; set; }
        public bool SyncNameToPerCon { get; set; }
        public bool SyncPhoneToPerCon { get; set; }
        public string? WebSite { get; set; }
        public string? IM { get; set; }
        public string? Twitter { get; set; }
        public string? LinkedIn { get; set; }
        public string? FaceBook { get; set; }
        public string? WebLink1 { get; set; }
        public string? WebLink2 { get; set; }
        public string? WebLink3 { get; set; }
        public string? WebLink4 { get; set; }
        public string? WebLink5 { get; set; }
        public int SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public bool PrimaryContact { get; set; }
        public bool GlbFlag { get; set; }
        public string? VendCntAttrStrng { get; set; }
        public string? GlbLink { get; set; }
        public string? PerConName { get; set; }
        public int BitFlag { get; set; }
        public string? PurPointZip { get; set; }
        public string? PurPointAddress2 { get; set; }
        public string? PurPointState { get; set; }
        public string? PurPointName { get; set; }
        public int PurPointPrimPCon { get; set; }
        public string? PurPointCity { get; set; }
        public string? PurPointAddress1 { get; set; }
        public string? PurPointCountry { get; set; }
        public string? PurPointAddress3 { get; set; }
        public string? RoleCodeRoleDescription { get; set; }
        public string? VendorNumDefaultFOB { get; set; }
        public string? VendorNumState { get; set; }
        public string? VendorNumAddress2 { get; set; }
        public string? VendorNumAddress1 { get; set; }
        public string? VendorNumVendorID { get; set; }
        public string? VendorNumAddress3 { get; set; }
        public string? VendorNumCurrencyCode { get; set; }
        public string? VendorNumCountry { get; set; }
        public string? VendorNumZIP { get; set; }
        public string? VendorNumName { get; set; }
        public string? VendorNumCity { get; set; }
        public string? VendorNumTermsCode { get; set; }
        public string? RowMod { get; set; }
        public string? UD_SysRevID { get; set; }
        public bool CheckBox01 { get; set; }
        public bool CheckBox02 { get; set; }
        public bool CheckBox03 { get; set; }
        public bool KPOContact_c { get; set; }
        public List<VendCntAttch>? VendCntAttches { get; set; }
    }

    public class VendCntAttch
    {
        public string? Company { get; set; }
        public int VendorNum { get; set; }
        public string? PurPoint { get; set; }
        public int ConNum { get; set; }
        public int DrawingSeq { get; set; }
        public int XFileRefNum { get; set; }
        public int SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public string? ForeignSysRowID { get; set; }
        public string? DrawDesc { get; set; }
        public string? FileName { get; set; }
        public string? PDMDocID { get; set; }
        public string? DocTypeID { get; set; }
        public string? RowMod { get; set; }
    }

    public class VendCntMain
    {
        public string? Company { get; set; }
        public int VendorNum { get; set; }
        public string? PurPoint { get; set; }
        public int ConNum { get; set; }
        public string? Name { get; set; }
        public string? Func { get; set; }
        public string? FaxNum { get; set; }
        public string? PhoneNum { get; set; }
        public string? EmailAddress { get; set; }
        public string? WebPassword { get; set; }
        public bool WebUser { get; set; }
        public string? RoleCode { get; set; }
        public string? CellPhoneNum { get; set; }
        public string? PagerNum { get; set; }
        public string? HomeNum { get; set; }
        public string? AltNum { get; set; }
        public string? ContactTitle { get; set; }
        public string? ReportsTo { get; set; }
        public string? Comment { get; set; }
        public bool NoContact { get; set; }
        public DateTime CreateDate { get; set; }
        public string? CreateDcdUserID { get; set; }
        public DateTime ChangeDate { get; set; }
        public string? ChangeDcdUserID { get; set; }
        public bool Inactive { get; set; }
        public string? FirstName { get; set; }
        public string? MiddleName { get; set; }
        public string? LastName { get; set; }
        public string? Prefix { get; set; }
        public string? Suffix { get; set; }
        public string? Initials { get; set; }
        public string? ExternalId { get; set; }
        public bool GlobalLock { get; set; }
        public int PerConID { get; set; }
        public bool SyncEmailToPerCon { get; set; }
        public bool SyncLinksToPerCon { get; set; }
        public bool SyncNameToPerCon { get; set; }
        public bool SyncPhoneToPerCon { get; set; }
        public string? WebSite { get; set; }
        public string? IM { get; set; }
        public string? Twitter { get; set; }
        public string? LinkedIn { get; set; }
        public string? FaceBook { get; set; }
        public string? WebLink1 { get; set; }
        public string? WebLink2 { get; set; }
        public string? WebLink3 { get; set; }
        public string? WebLink4 { get; set; }
        public string? WebLink5 { get; set; }
        public int SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public bool GlbFlag { get; set; }
        public bool PrimaryContact { get; set; }
        public string? VendCntAttrStrng { get; set; }
        public string? GlbLink { get; set; }
        public string? PerConName { get; set; }
        public int BitFlag { get; set; }
        public string? RoleCodeRoleDescription { get; set; }
        public string? RowMod { get; set; }
        public string? UD_SysRevID { get; set; }
        public bool CheckBox01 { get; set; }
        public bool CheckBox02 { get; set; }
        public bool CheckBox03 { get; set; }
        public bool KPOContact_c { get; set; }
    }

    public class VendorAttch
    {
        public string? Company { get; set; }
        public int VendorNum { get; set; }
        public int DrawingSeq { get; set; }
        public int XFileRefNum { get; set; }
        public int SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public string? ForeignSysRowID { get; set; }
        public string? DrawDesc { get; set; }
        public string? FileName { get; set; }
        public string? PDMDocID { get; set; }
        public string? DocTypeID { get; set; }
        public string? RowMod { get; set; }
    }

    public class VendorPP
    {
        public string? Company { get; set; }
        public string? PurPoint { get; set; }
        public string? Name { get; set; }
        public string? Address1 { get; set; }
        public string? Address2 { get; set; }
        public string? Address3 { get; set; }
        public string? City { get; set; }
        public string? State { get; set; }
        public string? Zip { get; set; }
        public string? Country { get; set; }
        public int VendorNum { get; set; }
        public int PrimPCon { get; set; }
        public int CountryNum { get; set; }
        public string? LangNameID { get; set; }
        public string? BorderCrossing { get; set; }
        public string? FormatStr { get; set; }
        public string? EMailAddress { get; set; }
        public string? ExternalId { get; set; }
        public string? TaxAuthorityCode { get; set; }
        public bool GlobalLock { get; set; }
        public string? EDICode { get; set; }
        public bool ResDelivery { get; set; }
        public bool SatDelivery { get; set; }
        public bool SatPickup { get; set; }
        public bool Hazmat { get; set; }
        public bool DocOnly { get; set; }
        public string? RefNotes { get; set; }
        public bool ApplyChrg { get; set; }
        public int ChrgAmount { get; set; }
        public bool COD { get; set; }
        public bool CODFreight { get; set; }
        public bool CODCheck { get; set; }
        public int CODAmount { get; set; }
        public string? GroundType { get; set; }
        public bool NotifyFlag { get; set; }
        public string? NotifyEMail { get; set; }
        public bool DeclaredIns { get; set; }
        public int DeclaredAmt { get; set; }
        public bool ServSignature { get; set; }
        public bool ServAlert { get; set; }
        public bool ServHomeDel { get; set; }
        public string? DeliveryType { get; set; }
        public DateTime ServDeliveryDate { get; set; }
        public string? ServPhone { get; set; }
        public string? ServInstruct { get; set; }
        public bool ServRelease { get; set; }
        public string? ServAuthNum { get; set; }
        public string? ServRef1 { get; set; }
        public string? ServRef2 { get; set; }
        public string? ServRef3 { get; set; }
        public string? ServRef4 { get; set; }
        public string? ServRef5 { get; set; }
        public bool OverrideCarrier { get; set; }
        public bool OverrideService { get; set; }
        public bool IndividualPackIDs { get; set; }
        public bool IntrntlShip { get; set; }
        public bool CertOfOrigin { get; set; }
        public bool CommercialInvoice { get; set; }
        public bool ShipExprtDeclartn { get; set; }
        public bool LetterOfInstr { get; set; }
        public string? FFID { get; set; }
        public string? FFCompName { get; set; }
        public string? FFContact { get; set; }
        public string? FFAddress1 { get; set; }
        public string? FFAddress2 { get; set; }
        public string? FFAddress3 { get; set; }
        public string? FFCity { get; set; }
        public string? FFState { get; set; }
        public string? FFZip { get; set; }
        public string? FFCountry { get; set; }
        public bool NonStdPkg { get; set; }
        public int DeliveryConf { get; set; }
        public bool AddlHdlgFlag { get; set; }
        public bool UPSQuantumView { get; set; }
        public string? UPSQVShipFromName { get; set; }
        public string? UPSQVMemo { get; set; }
        public string? FFPhoneNum { get; set; }
        public int FFCountryNum { get; set; }
        public string? LegalName { get; set; }
        public int SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public string? INExciseRegNumber { get; set; }
        public string? INExciseDivision { get; set; }
        public string? INExciseRange { get; set; }
        public string? INCommissionarate { get; set; }
        public string? INVATNumber { get; set; }
        public string? INServiceTaxRegNum { get; set; }
        public string? INTaxRegionCode { get; set; }
        public string? OrgRegCode { get; set; }
        public string? INTaxRegistrationID { get; set; }
        public string? MXMunicipio { get; set; }
        public string? GroupCode { get; set; }
        public bool IntegrationFlag { get; set; }
        public string? PhoneNum { get; set; }
        public bool PrimaryPP { get; set; }
        public string? VendAttrString { get; set; }
        public bool GlbFlag { get; set; }
        public string? GlbLink { get; set; }
        public string? SalesTaxID { get; set; }
        public string? ServiceTaxID { get; set; }
        public string? LangNameIDDescription { get; set; }
        public int BitFlag { get; set; }
        public string? CountryNumDescription { get; set; }
        public string? DeliveryTypeDescription { get; set; }
        public string? INTaxRegionCodeDescription { get; set; }
        public string? TACodeTaxAuthorityDescription { get; set; }
        public string? VendorNumState { get; set; }
        public string? VendorNumAddress3 { get; set; }
        public string? VendorNumAddress2 { get; set; }
        public string? VendorNumDefaultFOB { get; set; }
        public string? VendorNumCurrencyCode { get; set; }
        public string? VendorNumAddress1 { get; set; }
        public string? VendorNumCity { get; set; }
        public string? VendorNumVendorID { get; set; }
        public string? VendorNumZIP { get; set; }
        public string? VendorNumCountry { get; set; }
        public string? VendorNumTermsCode { get; set; }
        public string? VendorNumName { get; set; }
        public string? RowMod { get; set; }
        public string? UD_SysRevID { get; set; }
        public string? pbsOperatingHours_c { get; set; }
        public List<VenPPMFBill>? VenPPMFBills { get; set; }
        public List<VenPPUPSEmail>? VenPPUPSEmails { get; set; }
        public List<VendPPRestriction>? VendPPRestrictions { get; set; }
        public List<VendCnt>? VendCnts { get; set; }
    }

    public class VendPPRestriction
    {
        public string? Company { get; set; }
        public int VendorNum { get; set; }
        public string? PurPoint { get; set; }
        public string? RestrictionTypeID { get; set; }
        public int SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public int BitFlag { get; set; }
        public string? PurPointName { get; set; }
        public string? PurPointState { get; set; }
        public string? PurPointAddress3 { get; set; }
        public string? PurPointAddress1 { get; set; }
        public string? PurPointZip { get; set; }
        public string? PurPointCity { get; set; }
        public string? PurPointAddress2 { get; set; }
        public int PurPointPrimPCon { get; set; }
        public string? PurPointCountry { get; set; }
        public string? RestrictionTypeDescription { get; set; }
        public string? VendorNumCountry { get; set; }
        public string? VendorNumTermsCode { get; set; }
        public string? VendorNumCurrencyCode { get; set; }
        public string? VendorNumZIP { get; set; }
        public string? VendorNumVendorID { get; set; }
        public string? VendorNumAddress2 { get; set; }
        public string? VendorNumAddress1 { get; set; }
        public string? VendorNumAddress3 { get; set; }
        public string? VendorNumDefaultFOB { get; set; }
        public string? VendorNumCity { get; set; }
        public string? VendorNumName { get; set; }
        public string? VendorNumState { get; set; }
        public string? RowMod { get; set; }
    }

    public class VendRestriction
    {
        public string? Company { get; set; }
        public int VendorNum { get; set; }
        public string? RestrictionTypeID { get; set; }
        public int SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public int BitFlag { get; set; }
        public string? RestrictionTypeDescription { get; set; }
        public string? VendorNumVendorID { get; set; }
        public string? VendorNumCurrencyCode { get; set; }
        public string? VendorNumZIP { get; set; }
        public string? VendorNumCity { get; set; }
        public string? VendorNumAddress2 { get; set; }
        public string? VendorNumDefaultFOB { get; set; }
        public string? VendorNumAddress3 { get; set; }
        public string? VendorNumCountry { get; set; }
        public string? VendorNumTermsCode { get; set; }
        public string? VendorNumAddress1 { get; set; }
        public string? VendorNumName { get; set; }
        public string? VendorNumState { get; set; }
        public string? RowMod { get; set; }
    }

    public class VenMFBill
    {
        public string? Company { get; set; }
        public int VendorNum { get; set; }
        public string? PayBTFlag { get; set; }
        public string? PayTypeDesc { get; set; }
        public string? PayAccount { get; set; }
        public string? PayBTAddress1 { get; set; }
        public string? PayBTAddress2 { get; set; }
        public string? PayBTAddress3 { get; set; }
        public string? PayBTCity { get; set; }
        public string? PayBTState { get; set; }
        public string? PayBTZip { get; set; }
        public string? PayBTCountry { get; set; }
        public int PayBTCountryNum { get; set; }
        public string? PayBTPhone { get; set; }
        public int SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public int BitFlag { get; set; }
        public string? PayBTCountryNumDescription { get; set; }
        public string? RowMod { get; set; }
    }

    public class VenPPMFBill
    {
        public string? Company { get; set; }
        public int VendorNum { get; set; }
        public string? PurPoint { get; set; }
        public string? PayBTFlag { get; set; }
        public string? PayTypeDesc { get; set; }
        public string? PayAccount { get; set; }
        public string? PayBTAddress1 { get; set; }
        public string? PayBTAddress2 { get; set; }
        public string? PayBTAddress3 { get; set; }
        public string? PayBTCity { get; set; }
        public string? PayBTZip { get; set; }
        public string? PayBTState { get; set; }
        public string? PayBTCountry { get; set; }
        public int PayBTCountryNum { get; set; }
        public string? PayBTPhone { get; set; }
        public int SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public int BitFlag { get; set; }
        public string? PayBTCountryNumDescription { get; set; }
        public string? RowMod { get; set; }
    }

    public class VenPPUPSEmail
    {
        public string? Company { get; set; }
        public int VendorNum { get; set; }
        public string? PurPoint { get; set; }
        public int UPSQVSeq { get; set; }
        public string? EmailAddress { get; set; }
        public bool ShipmentNotify { get; set; }
        public bool FailureNotify { get; set; }
        public bool DeliveryNotify { get; set; }
        public int SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public bool EnableQuantumView { get; set; }
        public int BitFlag { get; set; }
        public string? RowMod { get; set; }
    }

    public class VenUPSEmail
    {
        public string? Company { get; set; }
        public int VendorNum { get; set; }
        public int UPSQVSeq { get; set; }
        public string? EmailAddress { get; set; }
        public bool ShipmentNotify { get; set; }
        public bool FailureNotify { get; set; }
        public bool DeliveryNotify { get; set; }
        public int SysRevID { get; set; }
        public string? SysRowID { get; set; }
        public bool EnableQuantumView { get; set; }
        public int BitFlag { get; set; }
        public string? RowMod { get; set; }
    }


}
